---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-user-renovate
spec:
  refreshPolicy: Periodic
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: postgres-user-renovate
    creationPolicy: Owner
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        user: renovate
        username: renovate
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: andtkeb6y2rfszjfubuwmclz4i
        property: password
