apiVersion: v1
kind: Secret
metadata:
  name: jellyfin-nas
stringData:
  NAS_SERVER: ENC[AES256_GCM,data:wZkgytAMbTu6XqTUm0pUTLE2mP5K,iv:55bcqJATTvT0jkospFZxsf5bdEWawyaDhfboj2tRYPY=,tag:euJWohZh4fXVjOPXxcaMNQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dVB2ZCtSQUxDa2pjck5s
        L0Z6V0ZIWlhmUmR2M1ZFMGM0bmxvMGlWNGpFClN3dXFybHE4SGxiMHN5VmRrT0Ju
        Um9CTTVXYjJxRUxiMHg0eGkza1FnV28KLS0tIFZQRTlETVUyZkNFcGt6d05ZRU14
        M210TEcyTXhHckNrSEJoRmQ2a3lrVkkK/Fuhrs34ph6wRVQJ0CWo4PwEsHYOYNlW
        m+uOa5qcvBpFXyco589dwBdq7ZNwl9DM2wFKbRrQR7+4SsK3UzKt7w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1d8dtvf39qwejljcn0jj7f29xtlnuav9sagfwy76g2asc0d4zjpqsu0s3pd
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-30T16:21:02Z"
  mac: ENC[AES256_GCM,data:smZPmNq33veV3NejF8xvYTfxN1vZRoseNFPkAFFRt3IS7zqY27tq2CGUpxM9FRYOEMFARnC86pSpLOzlakKPUnBAXgiPMhp3CHeg3mYiqemMK/F6C3G/EDY/1/bJIf3XBG3VIn+F+zJDyZrYf4qTDVXCn9mNGCy0mYXYlyU/+RI=,iv:ESBSpt/LinMfpoETBJykxsE1MEk5VALo8YzvZOQPaI4=,tag:ecf5btTDSFnNrgmNF9bnCg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
