---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: miniflux
spec:
  refreshPolicy: Periodic
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: miniflux-secret
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        ADMIN_PASSWORD: "{{ .ADMIN_PASSWORD }}"
        ADMIN_USERNAME: "{{ .ADMIN_USERNAME }}"
        OAUTH2_CLIENT_ID: "{{ .miniflux_client_id }}"
        OAUTH2_CLIENT_SECRET: "{{ .miniflux_client_secret }}"
  dataFrom:
    - extract:
        key: miniflux
    - extract:
        key: authentik-oidc
