---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: multi-scrobbler
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: multi-scrobbler-secret
  dataFrom:
    - extract:
        key: multi-scrobbler
  data:
    - secretKey: LASTFM_API_KEY
      remoteRef:
        key: lastfm
        property: LASTFM_API_KEY
    - secretKey: LASTFM_SECRET
      remoteRef:
        key: lastfm
        property: LASTFM_SHARED_SECRET
