---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crowdsec
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: crowdsec
    template:
      engineVersion: v2
      data:
        CROWDSEC_REGISTRATION_TOKEN: "{{ .registration_token }}"
        BOUNCER_KEY_fedora-nft: "{{ .bouncer_key_fedora_nft }}"
  dataFrom:
    - extract:
        key: crowdsec
