name-template: "Release v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "Community Contributions"
    labels:
      - "community"
  - title: "Helm Chart(s)"
    labels:
      - "renovate/helm"
  - title: "Github Actions"
    labels:
      - "renovate/github-action"
  - title: "Container(s)"
    labels:
      - "renovate/container"
  - title: "Features"
    labels:
      - "feature_request"
      - "enhancement"
  - title: "Bug Fixes"
    labels:
      - "bug"
  - title: "Maintenance"
    labels:
      - "chore"
      - "documentation"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&'
exclude-labels:
  - "skip-changelog"
version-resolver:
  major:
    labels:
      - "type/major"
  minor:
    labels:
      - "type/minor"
  patch:
    labels:
      - "type/patch"
  default: patch
template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
