---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: csi-driver-smb
  namespace: kube-system # Required for Renovate lookups
spec:
  interval: 12h
  url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-smb
spec:
  interval: 12h
  chart:
    spec:
      chart: csi-driver-smb
      version: v1.17.0
      sourceRef:
        kind: HelmRepository
        name: csi-driver-smb
        namespace: kube-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controller:
      runOnControlPlane: true
