---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.35.0-standalone-strict/service.json
apiVersion: v1
kind: Service
metadata:
  name: fluent-bit-syslog
  annotations:
    lbipam.cilium.io/ips: "10.60.80.54"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/instance: fluent-bit
  ports:
    - name: syslog-udp
      port: 514
      targetPort: 5140
      protocol: UDP
    - name: talos-niobe
      port: 5141
      targetPort: 5141
      protocol: TCP
    - name: talos-trinity
      port: 5142
      targetPort: 5142
      protocol: TCP
    - name: talos-ghost
      port: 5143
      targetPort: 5143
      protocol: TCP
