---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: descheduler
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.33.0
  url: oci://ghcr.io/home-operations/charts-mirror/descheduler
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: descheduler
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: descheduler
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    replicas: 2
    kind: Deployment
    deschedulerPolicyAPIVersion: descheduler/v1alpha2
    deschedulerPolicy:
      maxNoOfPodsToEvictPerNode: 2
      maxNoOfPodsToEvictTotal: 20
      profiles:
        - name: balance
          pluginConfig:
            - name: DefaultEvictor
              args:
                evictFailedBarePods: true
                evictSystemCriticalPods: false
                nodeFit: true
                priorityThreshold:
                  value: 1000000000
            - name: LowNodeUtilization
              args:
                thresholds:
                  cpu: 10
                  memory: 20
                  pods: 20
                targetThresholds:
                  cpu: 30
                  memory: 50
                  pods: 80
                evictionLimits:
                  node: 5
                evictableNamespaces:
                  exclude:
                    - kube-system
                    - monitoring
            - name: RemoveFailedPods
              args:
                excludeOwnerKinds:
                  - Job
                includingInitContainers: true
                minPodLifetimeSeconds: 1800
                reasons:
                  - ContainerStatusUnknown
                  - NodeAffinity
                  - NodeShutdown
                  - Terminated
                  - UnexpectedAdmissionError
            - name: RemovePodsViolatingNodeAffinity
              args:
                nodeAffinityType:
                  - requiredDuringSchedulingIgnoredDuringExecution
            - name: RemovePodsViolatingNodeTaints
            - name: RemovePodsViolatingInterPodAntiAffinity
          plugins:
            balance:
              enabled:
                - LowNodeUtilization
                - RemovePodsViolatingTopologySpreadConstraint
            deschedule:
              enabled:
                - RemoveFailedPods
                - RemovePodsViolatingNodeAffinity
                - RemovePodsViolatingNodeTaints
                - RemovePodsViolatingInterPodAntiAffinity
    service:
      enabled: true
    serviceMonitor:
      enabled: true
    leaderElection:
      enabled: true
