---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: cloudnative-pg-cluster
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.3.0
  url: oci://ghcr.io/cloudnative-pg/charts/cluster
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg-cluster
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: cloudnative-pg-cluster
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    type: postgresql
    mode: standalone
    cluster:
      instances: 2
      affinity:
        topologyKey: kubernetes.io/hostname
      storage:
        storageClass: smb-cnpg
      monitoring:
        enabled: true
        podMonitor:
          enabled: true
        prometheusRule:
          enabled: true
    backups:
      enabled: true
      provider: azure
      azure:
        storageAccount: matrixpgbackup
        containerName: pg-backups
        path: /v1
      secret:
        create: false
        name: pg-azure-backup-secret
      scheduledBackups:
        - name: daily-backup # Daily at midnight
          schedule: "0 0 0 * * *" # Daily at midnight
          backupOwnerReference: self
      retentionPolicy: "30d"
