---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: searxng
spec:
  chartRef:
    kind: OCIRepository
    name: searxng
  interval: 1h
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      searxng:
        annotations:
          reloader.stakater.com/auto: "true"
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: docker.io/searxng/searxng
              tag: 2026.3.17-2bb8ac17c
            env:
              SEARXNG_BASE_URL: "https://searxng.${SECRET_DOMAIN}"
            envFrom:
              - secretRef:
                  name: searxng-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: &port 8080
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 977
        runAsGroup: 977
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      config:
        type: configMap
        name: searxng-config
        globalMounts:
          - path: /etc/searxng/settings.yml
            subPath: settings.yml
            readOnly: true
          - path: /etc/searxng/limiter.toml
            subPath: limiter.toml
            readOnly: true
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
      branding:
        type: configMap
        name: searxng-branding
        globalMounts:
          - path: /usr/local/searxng/searx/static/themes/simple/img/searxng.svg
            subPath: searxng.svg
            readOnly: true
          - path: /usr/local/searxng/searx/static/themes/simple/img/searxng.png
            subPath: searxng.png
            readOnly: true
          - path: /usr/local/searxng/searx/static/themes/simple/img/favicon.png
            subPath: favicon.png
            readOnly: true
      cache:
        type: emptyDir
        globalMounts:
          - path: /var/cache/searxng
