---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
configMapGenerator:
  - name: searxng-config
    files:
      - settings.yml=./resources/settings.yml
      - limiter.toml=./resources/limiter.toml
  - name: searxng-branding
    files:
      - searxng.svg=./resources/searxng.svg
      - searxng.png=./resources/searxng.png
      - favicon.png=./resources/favicon.png
generatorOptions:
  disableNameSuffixHash: true
