---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  refreshInterval: 5m
  target:
    name: renovate
    template:
      type: Opaque
      data:
        RENOVATE_TOKEN: "{{ .RENOVATE_TOKEN }}"
        RENOVATE_AUTODISCOVER_FILTER: "{{ .RENOVATE_AUTODISCOVER_FILTER }}"
  dataFrom:
    - extract:
        key: renovate
