---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  refreshInterval: 5m
  target:
    name: renovate
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
      data:
        MEND_RNV_GITLAB_PAT: "{{ .RENOVATE_TOKEN }}"
        MEND_RNV_LICENSE_KEY: "{{ .RENOVATE_LICENSE_KEY }}"
        MEND_RNV_WEBHOOK_SECRET: "{{ .MEND_RNV_WEBHOOK_SECRET }}"
        MEND_RNV_AUTODISCOVER_FILTER: "{{ .RENOVATE_AUTODISCOVER_FILTER }}"
  data:
    - secretKey: RENOVATE_TOKEN
      remoteRef:
        key: mdrzf3cllqhtgqnr7hmuu4pmeu
        property: RENOVATE_TOKEN
    - secretKey: RENOVATE_AUTODISCOVER_FILTER
      remoteRef:
        key: mdrzf3cllqhtgqnr7hmuu4pmeu
        property: RENOVATE_AUTODISCOVER_FILTER
    - secretKey: MEND_RNV_WEBHOOK_SECRET
      remoteRef:
        key: mdrzf3cllqhtgqnr7hmuu4pmeu
        property: MEND_RNV_WEBHOOK_SECRET
    - secretKey: RENOVATE_LICENSE_KEY
      remoteRef:
        key: mdrzf3cllqhtgqnr7hmuu4pmeu
        property: RENOVATE_LICENSE_KEY
