---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: renovate
spec:
  chartRef:
    kind: OCIRepository
    name: renovate-app-template
  interval: 1h
  upgrade:
    force: true
  values:
    controllers:
      renovate:
        annotations:
          reloader.stakater.com/auto: "true"
        strategy: Recreate
        containers:
          renovate:
            image:
              repository: ghcr.io/mend/renovate-ce
              tag: 15.0.0-full@sha256:6ee8e044233feaecd8a11ce5205225ea40e0918aabaefc9d8088ed739cea5e01
            env:
              LOG_LEVEL: debug
              RENOVATE_ONBOARDING_CONFIG: '{"$schema":"https://docs.renovatebot.com/renovate-schema.json","extends":["config:best-practices"]}'
              MEND_RNV_PLATFORM: gitlab
              MEND_RNV_ENDPOINT: https://gitlab.melotic.dev/api/v4/
              MEND_RNV_ACCEPT_TOS: "y"
              MEND_RNV_WEBHOOK_URL: https://renovate-webhook.melotic.dev/webhook
              MEND_RNV_CRON_JOB_SCHEDULER_ALL: "0 * * * *"
              MEND_RNV_CRON_APP_SYNC: "0 */4 * * *"
              MEND_RNV_DATA_HANDLER_TYPE: postgresql
              PGHOST: postgres-cluster-pooler-rw.database.svc.cluster.local
              PGPORT: "5432"
              PGDATABASE: renovate
              PGUSER: renovate
              PGPASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: renovate-postgres
                    key: password
              GITHUB_COM_TOKEN:
                valueFrom:
                  secretKeyRef:
                    name: github-status-token-secret
                    key: token
            envFrom:
              - secretRef:
                  name: renovate
            ports:
              - name: http
                containerPort: 8080
                protocol: TCP
            probes:
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: http
                  periodSeconds: 5
                  timeoutSeconds: 1
                  failureThreshold: 60
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: http
                  initialDelaySeconds: 2
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
                  successThreshold: 1
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: http
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
                  successThreshold: 1
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                memory: 2Gi
    defaultPodOptions:
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 60
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values: ["k8s-ghost"]
    serviceAccount:
      default:
        enabled: false
    service:
      app:
        controller: renovate
        ports:
          http:
            port: 8080
            targetPort: http
            protocol: TCP
    configMaps:
      config:
        data:
          config.js: |-
            module.exports = {
              // Enter self-hosted configuration options here.
              // https://docs.renovatebot.com/self-hosted-configuration/
            }
    persistence:
      config:
        type: configMap
        identifier: config
        globalMounts:
          - path: /usr/src/app/config.js
            subPath: config.js
            readOnly: true
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
