---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./01-require-namespace-psa-labels.yaml
  - ./07-disallow-untrusted-images.yaml
  - ./08-require-image-registry-allowlist.yaml
  - ./09-prepend-default-registry.yaml
