---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "${APP}-postgres"
spec:
  refreshPolicy: Periodic
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: "${APP}-postgres"
    creationPolicy: Owner
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: kubernetes.io/basic-auth
      data:
        dbname: "${PG_DATABASE:=${APP}}"
        host: "${PG_HOST:=postgres-cluster-rw.database.svc.cluster.local}"
        jdbc-uri: 'jdbc:postgresql://${PG_HOST:=postgres-cluster-rw.database.svc.cluster.local}:5432/${PG_DATABASE:=${APP}}?user=${PG_USER:=${APP}}&password={{ .password | urlquery }}'
        password: "{{ .password }}"
        pgpass: '${PG_HOST:=postgres-cluster-rw.database.svc.cluster.local}:5432:${PG_DATABASE:=${APP}}:${PG_USER:=${APP}}:{{ .password | replace "\\" "\\\\" | replace ":" "\\:" }}'
        port: "5432"
        uri: 'postgresql://${PG_USER:=${APP}}:{{ .password | urlquery }}@${PG_HOST:=postgres-cluster-rw.database.svc.cluster.local}:5432/${PG_DATABASE:=${APP}}'
        user: "${PG_USER:=${APP}}"
        username: "${PG_USER:=${APP}}"
  dataFrom:
    - extract:
        key: "${ONEPASSWORD_ITEM:=${APP}-postgres}"
