---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ./externalsecret.yaml
  - ./database.yaml

patchesJson6902:
  - target:
      group: postgresql.cnpg.io
      version: v1
      kind: Cluster
      name: ${CLUSTER_NAME}
      namespace: ${CLUSTER_NS}
    path: role-patch.json6902.yaml
