---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kopia-azure-sync
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: kopia-azure-sync-secret
    template:
      data:
        KOPIA_PASSWORD: "{{ .KOPIA_PASSWORD }}"
        AZURE_STORAGE_ACCOUNT: "{{ .AZURE_ACCOUNT_NAME }}"
        AZURE_SAS_TOKEN: "{{ .AZURE_SAS_TOKEN }}"
  dataFrom:
    - extract:
        key: volsync-template
    - extract:
        key: nas-backup-azure
