---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: csi-driver-nfs
spec:
  interval: 1h
  url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-nfs
spec:
  chart:
    spec:
      chart: csi-driver-nfs
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
      version: 4.12.1
  interval: 1h
  values:
    storageClass:
      create: true
      name: nfs-construct
      parameters:
        server: construct.${SECRET_DOMAIN}
        share: /var/nfs/shared/k8s
      mountOptions:
        - nfsvers=3
        - proto=tcp
        - rsize=1048576
        - wsize=1048576
        - hard
        - timeo=600
        - retrans=2
        - nconnect=4
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
