---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: csi-driver-nfs
  namespace: kube-system # Required for Renovate lookups
spec:
  interval: 12h
  url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-nfs
spec:
  interval: 12h
  chart:
    spec:
      chart: csi-driver-nfs
      version: 4.11.0
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
        namespace: kube-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    externalSnapshotter:
      enabled: true
    storageClass:
      create: true
      name: nfs-csi
      parameters:
        server: 192.168.1.24
        share: /var/nfs/shared/k8s
      reclaimPolicy: Delete
      volumeBindingMode: Immediate # maybe change this to WaitForFirstConsumer
      mountOptions:
        - vers=3
        - nolock
        - noatime
        - async
        - rsize=131072
        - wsize=131072
