---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-operator
spec:
  chartRef:
    kind: OCIRepository
    name: grafana-operator
  interval: 1h
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    dashboard:
      enabled: true
    image:
      tag: v5.25.0@sha256:bc572995823fcfc32d2e960a47324a87baae8e4c9f821b8564026243e73624f3
    serviceMonitor:
      enabled: true
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
      limits:
        memory: 128Mi
