# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: grafana-oauth-secret
stringData:
    client_id: ENC[AES256_GCM,data:mWTmuRFdUw==,iv:MFJI0Gx95uoRLNPwzqWgB5n2HMPta1Zp08qhrID8lZA=,tag:7q89vsOapuZlp4EI5vce7A==,type:str]
    client_secret: ENC[AES256_GCM,data:GrtMZVA8W+sVDr8SunARFxypHPCHHOWlS1Crkfc4/as=,iv:U+MXR18g7z9TId/8alHVvqNYEWMynJr8yphDlFnLoqc=,tag:6c8hILsSYqXZ6I/VLpbjhA==,type:str]
sops:
    age:
        - recipient: age1swl8rf4aqksyqrwuyum0ny7vq5a7mtna0n79umsrw7lkrh2859zqsx0mpk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArSExyWGRic2hUY0ZwNXBo
            RnpRMlp5NHZTak5DQUtxc2lGUStTNzhxMERBCktRVnhNVklDOGhib0dVYVF0NWJk
            WU5Qb3Urc2xUYU1zM1ZvL2MvU0NuYWcKLS0tIFVQUG5abTFQRDQ2clV3VHR6VC9O
            Q0JubXBET2hvZ0RibXBpNXk3dzN4cU0KmAvbAmrLK96ABywyiYwyTUqJEbOptLyI
            seG7UxZ3f3QWDrnYwrqLCDXPkogmQxBkHU7r/237rvFjd6AQIasC3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-15T04:30:13Z"
    mac: ENC[AES256_GCM,data:Dz6I/+3aGYa/DX6r8wA4RSKfzkh7mM0v8ZeNeRRsqJOUzJ0GvY4g9m4FOrqQHkkwFQ8/nD5fKKUeY3I+ZMkBWi13DetJPv48FdmILe6uPRjo8MUdYn90HURNwfhkLT2HO4HVZPjNuOxW4zkXaocUYgkVbDiN4f7ig4ltHrzu1o0=,iv:tLysRBLS+C2Sr5mDkGHypQcoFvxhpLHAww8QUylow+k=,tag:LtR/qWo+bHipSbZmaA2Ddw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.1
