---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-webhook
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: alertmanager-webhook-secret
    template:
      data:
        WEBHOOK_URL: "{{ .WEBHOOK_URL }}"
  dataFrom:
    - extract:
        key: alertmanager
