---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik-pg-cluster
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: cloudnative-pg-cluster
    namespace: databases
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    type: postgresql
    mode: standalone
    cluster:
      instances: 3
      affinity:
        topologyKey: kubernetes.io/hostname
      storage:
        storageClass: smb-cnpg
      monitoring:
        enabled: true
        podMonitor:
          enabled: true
        prometheusRule:
          enabled: true
    # TODO: move secret into default namespace
    # backups:
    #   enabled: true
    #   provider: azure
    #   azure:
    #     storageAccount: matrixpgbackup
    #     containerName: pg-backups
    #     path: /authentik
    #   secret:
    #     create: false
    #     name: pg-azure-backup-secret
    #   scheduledBackups:
    #     - name: daily-backup # Daily at midnight
    #       schedule: "0 0 0 * * *" # Daily at midnight
    #       backupOwnerReference: self
    #   retentionPolicy: "30d"
