---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: authentik-secret
  data:
    - secretKey: GHIDRA_LDAP_TLS_CERTIFICATE_DATA
      remoteRef:
        key: melotic-dev-tls
        property: tls.crt
        decodingStrategy: Base64
    - secretKey: GHIDRA_LDAP_TLS_KEY_DATA
      remoteRef:
        key: melotic-dev-tls
        property: tls.key
        decodingStrategy: Base64
  dataFrom:
    - extract:
        key: authentik-oidc
      rewrite:
        - transform:
            template: "{{ .value | upper }}"
