---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
spec:
  chartRef:
    kind: OCIRepository
    name: authentik
  interval: 1h
  values:
    authentik:
      email:
        from: noreply@melotic.dev
        host: smtp-relay.default.svc.cluster.local
        port: 587
        use_ssl: false
        use_tls: false
      error_reporting:
        enabled: false
      postgresql:
        host: postgres-cluster-rw.database.svc.cluster.local
        password: file:///postgres-creds/password
        user: file:///postgres-creds/username
    blueprints:
      configMaps:
        - authentik-blueprints
    geoip:
      enabled: true
      existingSecret:
        accountId: MAXMIND_ACCOUNT_ID
        licenseKey: MAXMIND_LICENSE_KEY
        secretName: authentik-secret
      volumeMounts:
        - mountPath: /tmp
          name: tmp
      resources:
        requests:
          cpu: 5m
          memory: 64Mi
        limits:
          memory: 128Mi
      containerSecurityContext: &containerSecurityContext
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities: { drop: ["ALL"] }
    prometheus:
      rules:
        enabled: true
    server:
      priorityClassName: cluster-critical
      securityContext: &podSecurityContext
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      containerSecurityContext: *containerSecurityContext
      resources:
        requests:
          cpu: 100m
          memory: 1Gi
        limits:
          memory: 1536Mi
      envFrom:
        - secretRef:
            name: authentik-secret
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      podAnnotations:
        reloader.stakater.com/auto: "true"
      route:
        main:
          enabled: true
          hostnames:
            - sso.melotic.dev
          parentRefs:
            - name: envoy-internal
              namespace: network
              sectionName: https
      volumeMounts: &volumeMounts
        - mountPath: /postgres-creds
          name: postgres-creds
          readOnly: true
        - mountPath: /data
          name: data
        - mountPath: /tmp
          name: tmp
      volumes: &volumes
        - name: postgres-creds
          secret:
            secretName: postgres-cluster-app
        - name: data
          persistentVolumeClaim:
            claimName: authentik-data
        - name: tmp
          emptyDir: {}
    worker:
      priorityClassName: cluster-critical
      securityContext: *podSecurityContext
      containerSecurityContext: *containerSecurityContext
      resources:
        requests:
          cpu: 150m
          memory: 640Mi
        limits:
          memory: 1Gi
      envFrom:
        - secretRef:
            name: authentik-secret
      podAnnotations:
        reloader.stakater.com/auto: "true"
      volumeMounts: *volumeMounts
      volumes: *volumes
