---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  - ./pvc.yaml
  - ./referencegrant.yaml
configMapGenerator:
  - name: authentik-blueprints
    files:
      - grafana.yaml=./blueprints/grafana.yaml
      - harbor.yaml=./blueprints/harbor.yaml
      - forgejo.yaml=./blueprints/forgejo.yaml
      - paperless-ngx.yaml=./blueprints/paperless-ngx.yaml
      - longhorn.yaml=./blueprints/longhorn.yaml
      - victoria-metrics.yaml=./blueprints/victoria-metrics.yaml
      - victoria-logs.yaml=./blueprints/victoria-logs.yaml
      - alertmanager.yaml=./blueprints/alertmanager.yaml
      - slskd.yaml=./blueprints/slskd.yaml
      - echo.yaml=./blueprints/echo.yaml
      - outpost.yaml=./blueprints/outpost.yaml
      - flow-login.yaml=./blueprints/flow-login.yaml
      - brand.yaml=./blueprints/brand.yaml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
