# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: authentik-email-secret
stringData:
    AUTHENTIK_EMAIL__FROM: ENC[AES256_GCM,data:CYjCL168vdXvNsrqcF7mqrQ=,iv:yryeOhjw8P7fBWU98hoeQZBTVY58AWh+02wKQeTRsWg=,tag:0FFv0ihmdVzrV4qr2iCJ3g==,type:str]
    AUTHENTIK_EMAIL__HOST: ENC[AES256_GCM,data:4cuofDAG3WxQtyo8Wq7+,iv:W8XcTb8lwkT9CBpeGqV/9EdL3hZG3Y2yyxw5s0hTT0E=,tag:bWxyEsKxdLt0By8IxyFC7w==,type:str]
    AUTHENTIK_EMAIL__PASSWORD: ENC[AES256_GCM,data:1v6NgA7JJ0rkGTl+hS1BnrScbg==,iv:Xqp0LTX/IxpNzEPnRQzn/wNUPbrtiKAas5IGM0fneDM=,tag:ebxTsmFTbn631BUToL62ug==,type:str]
    AUTHENTIK_EMAIL__PORT: ENC[AES256_GCM,data:Xsi0,iv:5X006RVAqnn1UfsQhFULzULCH1PEHBGVVCWNLMfwnB0=,tag:rIjKuxjm8mMjDVMZ0wfYaA==,type:str]
    AUTHENTIK_EMAIL__USE_SSL: ENC[AES256_GCM,data:iBV71w==,iv:2oyJseLJc/Mg7FHvkg06IwFgScbbVJ5ZSpCRcW2yjIY=,tag:Vn0syMSm+PzpkuFcjuQdew==,type:str]
    AUTHENTIK_EMAIL__USERNAME: ENC[AES256_GCM,data:32CCDLVnhmpnnL++kzq3GtQ=,iv:P8TV/uydnRT/w8paZEWocoeAkOaeeuxN3y6w8CYcTNM=,tag:JzANPLwi1n1W6Gq9Z45dHQ==,type:str]
sops:
    age:
        - recipient: age1swl8rf4aqksyqrwuyum0ny7vq5a7mtna0n79umsrw7lkrh2859zqsx0mpk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSzduQmdaWW01MWtYeWFk
            ODN1cEx2cFhMWkRSRnM3dGlPcFZnME96cFRBCnJtOW8xR2R5TmVrdU5zQkdFbzVG
            TWF5NGR0Vjdxc3U0eEZ0QXJRQSsvV00KLS0tIFRTbmFCWTgvWEE3RnRqZTB2VUh5
            ZWJVdksxWFdBMC9TTGhncE1Id2JicjAKTuvWYUByF73oWAu72Zx2T5T44j2y5UZZ
            JI31CZe507Op9oSHYvfxhLspPrlphN6ZC4d/U/xLDnxtxdbpzWUKgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-27T04:37:46Z"
    mac: ENC[AES256_GCM,data:GMrQROWcsBzzmUTnRyrpYpxNqk5sd/5DGN1AmuLYifLe95ad3/OErPq/OCUHbnss96ajA1OwFxfHfwZKjLV7w0s5BdJh1EgkDbXC/7bFTpnH5QwfjHaS9weVkzzKMoRKb64cKE0VCYO8yibK3Uph7f1CS+HvGpvo0r5SVPUJXXs=,iv:ZQM4kUNjMLiQVErTxwKWCDBf1vdyt4fZGmVDLJq7dW0=,tag:HvUk/Fd5aO4diauiF/Nf5A==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
