---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: silence-operator
spec:
  chartRef:
    kind: OCIRepository
    name: silence-operator
  interval: 1h
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    alertmanagerAddress: http://alertmanager-operated.monitoring.svc.cluster.local:9093
    image:
      tag: 0.20.1@sha256:99f087838f39830f587ab7897708ad9155ccd71a5d71e76e81b9217e6eaa386f
    networkPolicy:
      enabled: false
