# yaml-language-server: $schema=https://raw.githubusercontent.com/cilium/cilium/refs/heads/main/install/kubernetes/cilium/values.schema.json
---
autoDirectNodeRoutes: true
bgpControlPlane:
  enabled: true
bpf:
  datapathMode: netkit
  masquerade: true
  preallocateMaps: true
cgroup:
  automount:
    enabled: false
  hostRoot: /sys/fs/cgroup
cni:
  # Required for pairing with Multus CNI
  exclusive: false
# NOTE: devices might need to be set if you have more than one active NIC on your hosts
# devices: eno+ eth+
dashboards:
  enabled: true
encryption:
  enabled: true
  nodeEncryption: true
  type: wireguard
endpointRoutes:
  enabled: true
envoy:
  enabled: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
  rollOutPods: true
gatewayAPI:
  enableAlpn: true
  enabled: true
hubble:
  enabled: true
  metrics:
    dashboards:
      enabled: true
    enabled:
      - dns
      - drop
      - flow
      - http
      - tcp
    serviceMonitor:
      enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
    ingress:
      className: internal
      enabled: true
      hosts:
        - hubble.${SECRET_DOMAIN}
ipam:
  mode: kubernetes
ipv4NativeRoutingCIDR: "10.60.0.0/16"
k8sServiceHost: 127.0.0.1
k8sServicePort: 7445
kubeProxyReplacement: true
kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
l2announcements:
  enabled: true
loadBalancer:
  algorithm: maglev
  mode: "dsr"
localRedirectPolicy: true
operator:
  dashboards:
    enabled: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
  replicas: 2
  rollOutPods: true
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    trustCRDsExist: true
rollOutCiliumPods: true
routingMode: native
securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - PERFMON
      - BPF
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
socketLB:
  hostNamespaceOnly: true
