---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: listenbrainz-discovery
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: listenbrainz-discovery-secret
  data:
    - secretKey: LZ_TOKEN
      remoteRef:
        key: multi-scrobbler
        property: LZ_TOKEN
    - secretKey: LZ_USER
      remoteRef:
        key: multi-scrobbler
        property: LZ_USER
    - secretKey: LIDARR_API_KEY
      remoteRef:
        key: lidarr
        property: LIDARR_API_KEY
