---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-access-tfvars
  namespace: network
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cf-access-tfvars
    template:
      engineVersion: v2
      data:
        cloudflare_api_token: "{{ .CLOUDFLARE_ZT_TOKEN | trim }}"
        account_id: "31bd6064f8c4bcc23fcb7eb49c171c98"
        oidc_client_id: "{{ .cloudflare_access_client_id }}"
        oidc_client_secret: "{{ .cloudflare_access_client_secret }}"
        operator_email: "{{ .ztna_operator_email }}"
  dataFrom:
    - extract:
        key: cloudflare
    - extract:
        key: authentik-oidc
