---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kopiur.home-operations.com/repositoryreplication_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: RepositoryReplication
metadata:
  name: volsync-azure
spec:
  sourceRef:
    kind: ClusterRepository
    name: volsync
  destination:
    azure:
      auth:
        secretRef:
          name: azure-mirror-creds
      container: nas-backup
      prefix: k8s/volsync/
      storageAccount: sthomeopsbackup
  schedule:
    cron: 30 8 * * *
    jitter: 1h
  sync:
    deleteExtra: true
    parallel: 2
