# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:znNBA/maHnzUNXLQNaVVeLRH/+8maFvamIEbrMTJAB4=,iv:tqo685DrrQ6XkKJk6jZ90QQ2ZoRg6sh3afvOCpIZ6T8=,tag:0znfmMEqid/2cq9U3N8lug==,type:str]
sops:
  age:
    - recipient: age1swl8rf4aqksyqrwuyum0ny7vq5a7mtna0n79umsrw7lkrh2859zqsx0mpk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhck9KNDI0YWk3V2orR2pB
        YVBhaWtkemZWOFVlVWdMWXJlb1lrWjJFelFrCmV3YUJmN0lkMVZuQ28rY0QvUWhH
        WnZxTG5SdHdQVkNwTExhNjJ3aDBNYUEKLS0tIFd5TlhZRG1uWVp2MTJoZXJ0Sm4w
        endqbzMydE5SS3pLa2RUMTlWTXRJbXcKU1eK2ceYkNxnb9T3GdTdRrtjp3KAp6jI
        GVba4D/0vc8HyY0XcV4h/E63bZ3rGuezS6MryawLzrHzjD3ZMowzdA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-13T23:56:17Z"
  mac: ENC[AES256_GCM,data:U5vq6QER4cAvmP/kbUfUg/gRfLGfHULhPVzdnu6TVZo9yRHbt8hAqQ7n9mPw83FKT0SC6/FuyK0FzCWcYJcq8iL2S1C+9rfu2icvuR3suTQoJVKUQ/mYbeniQBKhqA3asx/fTBq3XV6cMOXnQ+Qet41sMcbo39FgOidbgZ16+LM=,iv:NOOFmdV9h8hNeEUlsac9S/ivv69K1WaSoAfRNwbTyEc=,tag:LWo+U+CE96I3CHqzn5iLgA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.1
