# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:sRbGUDNSYGc/tS+K59KE6f4IYIzHL0lJgWoydJ2GNGg=,iv:ylP9rYQ+qXedMdvMl8YMmea1JgBisDl9F8qcFsbuWiQ=,tag:5RDQ5y/wylFZC+gJKFBh7w==,type:str]
sops:
  age:
    - recipient: age1d8dtvf39qwejljcn0jj7f29xtlnuav9sagfwy76g2asc0d4zjpqsu0s3pd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRQ2trcFhQVWQvbk90QTJJ
        SFJQSEkyaERQWTlleXBnMXFNYm51RFh2NnhVCmNISzVrNk41dEVrK3l6dktiMVpa
        RmNhamo4RjJhRWt2cW1vbVFlWUJsWWsKLS0tIGU3YmkzWElXbXZkWGtQU1EzTGtS
        QTB3TFRaRHdhelg5cXZmVm9IMTdaR3cK1KfzUvHDNHK9gEbrirTBK3ar1XsMovWT
        R14Z7anQq388xLZkoDaVAjtZyMqKKRlduY6oH7wgfNyZz6myb4gRUg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-01T03:32:16Z"
  mac: ENC[AES256_GCM,data:TpmPoa3mMo7UhnkHNfyFlgAyMNoq3q6/uCLJZc3k5Zvylz4OsGe6k2UjndMMlrwKGhrvEpoJRn7y1XugHcOTr8/ywYPHu4MyAmDSq2lRMrRrIVWU2yDOjEdG6rT7N1TQdeiATYDLSxPL7JTWG71rPOue15ptIFXMUA2zm8brqlw=,iv:7zFb4+zGVDyJhbKPEQGUMYBLV2qfCd/NPfD7Ze+l6zA=,tag:HhZ3W6mlpH5kDWU+AUi8ZQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
