use_default_settings: true
server:
  limiter: false
  public_instance: false
  image_proxy: true
  method: "GET"
valkey:
  url: "valkey://dragonfly.database.svc.cluster.local:6379/8"
search:
  autocomplete: "duckduckgo"
