---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/tuppr.home-operations.com/talosupgrade_v1alpha1.json
apiVersion: tuppr.home-operations.com/v1alpha1
kind: TalosUpgrade
metadata:
  name: talos
spec:
  talos:
    # renovate: datasource=docker depName=ghcr.io/siderolabs/installer
    version: v1.13.7
  policy:
    rebootMode: powercycle
  maintenance:
    windows:
      - duration: 8h
        start: 0 0 * * 1-5
        timezone: America/Chicago
  healthChecks:
    - apiVersion: v1
      kind: Node
      expr: |-
        status.conditions.filter(c, c.type == "Ready").all(c, c.status == "True")
      timeout: 10m
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      expr: |-
        status.conditions.filter(c, c.type == "Ready").all(c, c.status == "True")
      timeout: 10m
    - apiVersion: ceph.rook.io/v1
      kind: CephCluster
      name: rook-ceph
      namespace: rook-ceph
      expr: |-
        status.ceph.health == "HEALTH_OK"
      timeout: 15m
