---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-dns-tfvars
  namespace: network
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: tailscale-dns-tfvars
    template:
      engineVersion: v2
      data:
        oauth_client_id: "{{ .client_id }}"
        oauth_client_secret: "{{ .client_secret }}"
  dataFrom:
    - extract:
        key: tailscale-terraform
