---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: cloudnative-pg-cluster
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.3.0
  url: oci://ghcr.io/cloudnative-pg/charts/cluster
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg-cluster
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: cloudnative-pg-cluster
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: longhorn-release
      namespace: longhorn-system
  values:
    type: postgresql
    mode: standalone
    cluster:
      instances: 3
      imageName: ghcr.io/cloudnative-pg/postgresql:17.4@sha256:5abfcc284a440c091f01a89381bf4cdafdfd14038a2e6aa903c6f0508d211be3
      affinity:
        topologyKey: kubernetes.io/hostname
      storage:
        storageClass: longhorn-cnpg
      monitoring:
        enabled: true
        podMonitor:
          enabled: true
        prometheusRule:
          enabled: true
    backups:
      enabled: true
      provider: azure
      azure:
        containerName: pg-backups
        storageAccount: ${SECRET_AZURE_STORAGE_ACCOUNT}
        storageKey: ${SECRET_AZURE_STORAGE_KEY}
      secret:
        create: true
      scheduledBackups:
        - name: daily-backup # Daily at midnight
          schedule: "0 0 0 * * *" # Daily at midnight
          backupOwnerReference: self
      retentionPolicy: "30d"
