---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cloudnative-pg
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.24.0
  url: oci://ghcr.io/cloudnative-pg/charts/cloudnative-pg
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg-operator
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: cloudnative-pg
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    monitoring:
      podMonitorEnabled: true
      grafanaDashboard:
        create: true
    image:
      repository: ghcr.io/cloudnative-pg/cloudnative-pg
      tag: 1.26.0-rc2@sha256:2f07e6fd395cbec205be3fd8d9464cd8a47f7d83e57a92531ac4a2ab40c1132a
