# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: pg-azure-backup-secret
stringData:
    AZURE_STORAGE_ACCOUNT: ENC[AES256_GCM,data:xkOBxppEgng7qBEmKd4=,iv:75XKQD0Td+I2KLxcKb96yOoii4Lo1E4sUMCE60DM0Ww=,tag:EqxRGewo4LEI7x+zUag9lw==,type:str]
    AZURE_STORAGE_KEY: ENC[AES256_GCM,data:gpjJmxxUxPZClClrXJuJo12OaEk1NnPrTMnTTTJyfiALC+eJgFJFtb4v1Y20O87ojxQUmPVzZwGQ4Fa89MWgWP3a0OfWL0chX0iswuLB+ImW1BQECs+zsw==,iv:T6dm/8rznLSp7RssLvF8GTA47Rp9XSjI0/zEtPN4SEs=,tag:Ad8QNlpt7JhcGdo7CUhGmQ==,type:str]
sops:
    age:
        - recipient: age1swl8rf4aqksyqrwuyum0ny7vq5a7mtna0n79umsrw7lkrh2859zqsx0mpk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArSExyWGRic2hUY0ZwNXBo
            RnpRMlp5NHZTak5DQUtxc2lGUStTNzhxMERBCktRVnhNVklDOGhib0dVYVF0NWJk
            WU5Qb3Urc2xUYU1zM1ZvL2MvU0NuYWcKLS0tIFVQUG5abTFQRDQ2clV3VHR6VC9O
            Q0JubXBET2hvZ0RibXBpNXk3dzN4cU0KmAvbAmrLK96ABywyiYwyTUqJEbOptLyI
            seG7UxZ3f3QWDrnYwrqLCDXPkogmQxBkHU7r/237rvFjd6AQIasC3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-20T06:52:01Z"
    mac: ENC[AES256_GCM,data:OjzHmqUdrSuECxerkRQRjefwSiZOXUN00abZK3vP3bL7fvdslFGA03CuSI8bnydSc3ZKopIcW0VVLRyJSmPyUUwCXO4ESLAFJ2Aa6DroPXXRAFLeXLKA2128i3H9i92zhY9xXO1fZxAwah0YjKqwXLXlV8dOYiMfr+3YU6wiI0w=,iv:i5zS4+Hqh5cYHKdU+Hk+79sevTAMH2k9Gsmjrl5j98M=,tag:3j/mBedgKum/eK7dWxhQDw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.1
