---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: soularr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: soularr-secret
    template:
      data:
        config.ini: |
          [Lidarr]
          api_key = {{ .LIDARR_API_KEY }}
          host_url = http://lidarr.default.svc.cluster.local
          download_dir = /data/soulseek/complete
          disable_sync = False

          [Slskd]
          api_key = {{ .SLSKD_API_KEY }}
          host_url = http://slskd.default.svc.cluster.local:5030
          url_base = /
          download_dir = /data/soulseek/complete
          delete_searches = True
          stalled_timeout = 3600
          remote_queue_timeout = 300

          [Release Settings]
          use_most_common_tracknum = True
          allow_multi_disc = True
          accepted_countries = Europe,Japan,United Kingdom,United States,[Worldwide],Australia,Canada
          skip_region_check = False
          accepted_formats = CD,Digital Media

          [Search Settings]
          search_timeout = 5000
          maximum_peer_queue = 50
          minimum_peer_upload_speed = 100
          minimum_filename_match_ratio = 0.8
          allowed_filetypes = flac,mp3 320,mp3
          ignored_users =
          search_for_tracks = True
          album_prepend_artist = True
          track_prepend_artist = True
          search_type = incrementing_page
          number_of_albums_to_grab = 10
          remove_wanted_on_failure = False
          title_blacklist =
          search_blacklist =
          search_source = missing
          enable_search_denylist = False
          max_search_failures = 3

          [Download Settings]
          download_filtering = True
          use_extension_whitelist = False
          extensions_whitelist = lrc,nfo,txt

          [Logging]
          level = INFO
          format = [%(levelname)s|%(module)s|L%(lineno)d] %(asctime)s: %(message)s
          datefmt = %Y-%m-%dT%H:%M:%S%z
  dataFrom:
    - extract:
        key: soularr
