auth {
	com.sun.security.auth.module.LdapLoginModule REQUIRED
		userProvider="ldaps://${AUTHENTIK_LDAP_HOST}:636/${AUTHENTIK_LDAP_BASE_DN}"
		authIdentity="cn={USERNAME},ou=users,${AUTHENTIK_LDAP_BASE_DN}"
		debug=false;
};
