---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forejo-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: forejo-secrets
    template:
      type: Opaque
      data:
        SECRET_KEY: "{{ .SECRET_KEY }}"
        INTERNAL_TOKEN: "{{ .INTERNAL_TOKEN }}"
        LFS_JWT_SECRET: "{{ .LFS_JWT_SECRET }}"
  dataFrom:
    - extract:
        key: forejo-secrets
