---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: k8s-monitoring
spec:
  interval: 5m
  url: https://grafana.github.io/helm-charts
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-monitoring
spec:
  interval: 1h
  chart:
    spec:
      chart: k8s-monitoring
      version: 2.0.25
      sourceRef:
        kind: HelmRepository
        name: k8s-monitoring
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    cluster:
      name: kubernetes
    destinations:
      - name: loki
        type: loki
        url: http://loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push

    # Sources
    clusterEvents:
      enabled: true
      collector: alloy-logs
    nodeLogs:
      enabled: false
    podLogs:
      enabled: true
      gatherMethod: kubernetesApi
      collector: alloy-logs
      structuredMetadata:
        pod: pod # Set structured metadata "pod" from label "pod"

    # Collectors
    alloy-singleton:
      enabled: false
    alloy-metrics:
      enabled: false
    alloy-logs:
      enabled: true
      alloy:
        controller:
          podAnnotations:
            reloader.stakater.com/auto: "true"
        ingress:
          enabled: true
          ingressClassName: internal
          annotations:
            external-dns.alpha.kubernetes.io/hostname: "alloy.${SECRET_DOMAIN}"
          hosts:
            - "alloy.${SECRET_DOMAIN}"

        # required for kubernetes api
        mounts:
          varlog: false
    alloy-profiles:
      enabled: false
    alloy-receiver:
      enabled: false
