---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
  - ../../components/alerts
  - ../../components/common
resources:
  - ./atuin/ks.yaml
  - ./authentik/ks.yaml
  - ./echo/ks.yaml
  - ./forejo/ks.yaml
  - ./forejo-runner/ks.yaml
  - ./harbor/ks.yaml
  - ./home-assistant/ks.yaml
  - ./kopia-verify/ks.yaml
  - ./lidarr/ks.yaml
  - ./nas-backup/ks.yaml
  - ./paperless-ngx/ks.yaml
  - ./plex/ks.yaml
  - ./prowlarr/ks.yaml
  - ./radarr/ks.yaml
  - ./recyclarr/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./searxng/ks.yaml
  - ./seerr/ks.yaml
  - ./slskd/ks.yaml
  - ./smtp-relay/ks.yaml
  - ./sonarr/ks.yaml
  - ./tautulli/ks.yaml
