# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:GFjJHRmD1ctBXt51BFmRwxNV3rf4VQQUe1wXDnfr1jcN29Yj9u5H4u33b/OlRs5cehpv67f+FLnaz5PE3JnjT6q+WrNRy8xV77mH8da3tiPq92wOyuW/B+R3WYI8t3QggsZIXeoWiuiVCftImCj3IPntjCu5xalr/oyTOVVSmkTM3eDfVkfVTHrUPm5nteK1rfohLwpy/A/fr65Cjd+JmAwklC8+ae8/IaspqdYMZ0YY/231,iv:YQxxGaFAuDIv32QYhTUiRIv6gAR8lLu/c3LZk3hW0kw=,tag:Oq+en7J8vi9YMmtuEkKEVQ==,type:str]
sops:
  age:
    - recipient: age1d8dtvf39qwejljcn0jj7f29xtlnuav9sagfwy76g2asc0d4zjpqsu0s3pd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYU0NFWXFIYklwWFFuN1Jk
        dW96RVAralJIVWVyRGRXL0dsT0xPRitwOUVrCllRM0Q5TWxUS3d0OWNpaUFvVUQ2
        a0lna0NuRjlHZG5ndlpnMGpEWHRIdkEKLS0tIFJKR1BTR1BBR1BjQzVoaU9pUVA4
        RXRyTy92aGRqQm5qRXZVN251ZDM5ZVEKVJnrMB+5ObwE4Lv6LA1NsDJrXsIuIy55
        bvjzxT3dPIo+GHNydI0t468Ipa616+pA8anCV9Dj4DczfRB9i8x7Pw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-01T03:32:16Z"
  mac: ENC[AES256_GCM,data:hhyEtvDc3XVKIdkKwces+omqvbL7a8uyFdoTWRWMGYB8MLfOv0KFszrP+lHvNWXQpHqw+OnXRNOZQk/fytxYV9eQI2K156LFHJEKeXU7cT2rfiqoAnsIIflFff8+JUF4lxx2lu/XTZthgFVvCpYWdTmzqAV8g5U5Ckoe6U0gW6U=,iv:fep6Yn/fm5obAGWHvF9v10oQY7YIpcFJkdiANR+aYkU=,tag:WKsqo1osnDLT0yBQb4RHJA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
