---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/generators.external-secrets.io/password_v1alpha1.json
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: paperless-password
spec:
  allowRepeat: true
  encoding: "base64"
  length: 60
  noUpper: false
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-ngx
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: paperless-secret
    template:
      data:
        PAPERLESS_SECRET_KEY: "{{ .password }}"
        PAPERLESS_ADMIN_PASSWORD: "{{ .paperless_PAPERLESS_ADMIN_PASSWORD }}"
        PAPERLESS_SOCIALACCOUNT_PROVIDERS: |
          {"openid_connect": {"APPS": [{"provider_id": "authentik", "name": "authentik", "client_id": "{{ .paperless_oauth_client_id }}", "client_secret": "{{ .paperless_oauth_client_secret }}", "settings": {"server_url": "https://sso.melotic.dev/application/o/paperless-ngx/.well-known/openid-configuration"}}]}}
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: paperless-password
    - extract:
        key: paperless
      rewrite:
        - regexp:
            source: "(.*)"
            target: "paperless_$1"
