---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-ngx
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: paperless-secret
    template:
      data:
        PAPERLESS_SECRET_KEY: "{{ .paperless_password }}"
        PAPERLESS_ADMIN_PASSWORD: "{{ .paperless_PAPERLESS_ADMIN_PASSWORD }}"
        PAPERLESS_SOCIALACCOUNT_PROVIDERS: |
          {"openid_connect": {"OAUTH_PKCE_ENABLED": true, "APPS": [{"provider_id": "authentik", "name": "authentik", "client_id": "{{ .authentik_paperless_client_id }}", "secret": "{{ .authentik_paperless_client_secret }}", "settings": {"server_url": "https://sso.melotic.dev/application/o/paperless/.well-known/openid-configuration", "fetch_userinfo": true}}], "SCOPE": ["openid", "profile", "email"]}}
  dataFrom:
    - extract:
        key: paperless
      rewrite:
        - regexp:
            source: "(.*)"
            target: "paperless_$1"
    - extract:
        key: authentik-oidc
      rewrite:
        - regexp:
            source: "(.*)"
            target: "authentik_$1"
