---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless-ngx
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      paperless-ngx:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/paperless-ngx/paperless-ngx
              tag: 2.15.3
            env:
              PAPERLESS_DBHOST: cnpg-cluster-rw
              PAPERLESS_DBNAME: paperless
              PAPERLESS_DBUSER:
                valueFrom:
                  secretKeyRef:
                    name: cnpg-cluster-paperless
                    key: username
              PAPERLESS_DBPASS:
                valueFrom:
                  secretKeyRef:
                    name: cnpg-cluster-paperless
                    key: password
              PAPERLESS_REDIS: redis://dragonfly.default.svc.cluster.local:6379
              PAPERLESS_REDIS_PREFIX: paperless
              PAPERLESS_TIME_ZONE: America/Chicago
              PAPERLESS_URL: https://paperless.${SECRET_DOMAIN}
            envFrom:
              - secretRef:
                  name: paperless-secret
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
              readOnlyRootFilesystem: true
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi
    defaultPodOptions:
      securityContext:
        runAsGroup: 988
        runAsNonRoot: true
        runAsUser: 977
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: paperless-ngx
        ports:
          http:
            port: 8000
    ingress:
      app:
        className: internal
        enabled: true
        hosts:
          - host: paperless.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: paperless-ngx
                  port: 8000
    persistence:
      # This is where paperless stores all its data (search index, SQLite database, classification model, etc).
      data:
        type: persistentVolumeClaim
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 1Gi
        globalMounts:
          - path: /usr/src/paperless/data
            readOnly: false
      # This is where your documents and thumbnails are stored.
      media:
        type: persistentVolumeClaim
        storageClass: nfs-csi
        accessMode: ReadWriteOnce
        size: 8Gi
        globalMounts:
          - path: /usr/src/paperless/media
            readOnly: false

