---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app paperless-ngx
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      paperless-ngx:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          gotenberg:
            image:
              repository: docker.io/gotenberg/gotenberg
              tag: 8.20
            command:
              - "gotenberg"
              - "--chromium-disable-javascript=true"
              - "--chromium-allow-list=file:///tmp/.*"
          protonmail-bridge:
            image:
              repository: docker.io/shenxn/protonmail-bridge
              tag: 3.19.0-1
          tika:
            image:
              repository: docker.io/apache/tika
              tag: 3.1.0.0
          app:
            dependsOn:
              - gotenberg
              - protonmail-bridge
              - tika
            image:
              repository: ghcr.io/paperless-ngx/paperless-ngx
              tag: 2.15.3
            env:
              PAPERLESS_DBHOST: cnpg-cluster-rw
              PAPERLESS_DBNAME: paperless
              PAPERLESS_DBUSER:
                valueFrom:
                  secretKeyRef:
                    name: cnpg-cluster-paperless
                    key: username
              PAPERLESS_DBPASS:
                valueFrom:
                  secretKeyRef:
                    name: cnpg-cluster-paperless
                    key: password
              PAPERLESS_DISABLE_REGULAR_LOGIN: true
              PAPERLESS_REDIRECT_LOGIN_TO_SSO: true
              PAPERLESS_REDIS: redis://dragonfly.default.svc.cluster.local:6379
              PAPERLESS_REDIS_PREFIX: paperless
              PAPERLESS_TIKA_ENABLED: 1
              PAPERLESS_TIKA_ENDPOINT: http://tika:9998
              PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
              PAPERLESS_TIME_ZONE: America/Chicago
              PAPERLESS_URL: https://paperless.${SECRET_DOMAIN}
            envFrom:
              - secretRef:
                  name: paperless-secret
            resources:
              requests:
                cpu: 200m
                memory: 1Gi
              limits:
                cpu: 750m
                memory: 2.5Gi
    service:
      app:
        controller: *app
        ports:
          http:
            port: &port 8000
    route:
      app:
        enabled: true
        hostnames:
          - "paperless.${SECRET_DOMAIN}"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port
    persistence:
      # This is where paperless stores all its data (search index, SQLite database, classification model, etc).
      data:
        type: persistentVolumeClaim
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 1Gi
        advancedMounts:
          paperless-ngx:
            app:
              - path: /usr/src/paperless/data
                readOnly: false
      # This is where your documents and thumbnails are stored.
      media:
        type: persistentVolumeClaim
        storageClass: nfs-csi
        accessMode: ReadWriteOnce
        size: 8Gi
        advancedMounts:
          paperless-ngx:
            app:
              - path: /usr/src/paperless/media
                readOnly: false
      protonmail:
        type: persistentVolumeClaim
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 1Gi
        advancedMounts:
          paperless-ngx:
            protonmail-bridge:
              - path: /root
                readOnly: false
