---
version: 1
metadata:
  name: Open WebUI removal
entries:
  - model: authentik_core.application
    state: absent
    identifiers:
      slug: open-webui

  - model: authentik_providers_oauth2.oauth2provider
    state: absent
    identifiers:
      name: open-webui
