---
# yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
version: 1
metadata:
  name: Embedded Proxy Outpost
entries:
  - model: authentik_outposts.outpost
    identifiers:
      name: authentik Embedded Outpost
    attrs:
      name: authentik Embedded Outpost
      type: proxy
      managed: "goauthentik.io/outposts/embedded"
      providers:
        - !Find [authentik_providers_proxy.proxyprovider, [name, longhorn]]
        - !Find [
            authentik_providers_proxy.proxyprovider,
            [name, victoria-metrics],
          ]
        - !Find [authentik_providers_proxy.proxyprovider, [name, victoria-logs]]
        - !Find [authentik_providers_proxy.proxyprovider, [name, alertmanager]]
        - !Find [authentik_providers_proxy.proxyprovider, [name, slskd]]
        - !Find [authentik_providers_proxy.proxyprovider, [name, echo]]
        - !Find [authentik_providers_proxy.proxyprovider, [name, gatus]]

  - model: authentik_outposts.outpost
    identifiers:
      name: ghidra-server-ldap
    attrs:
      name: ghidra-server-ldap
      type: ldap
      service_connection:
        !Find [
          authentik_outposts.outpostserviceconnection,
          [name, "Local Kubernetes Cluster"],
        ]
      providers:
        - !Find [authentik_core.provider, [name, ghidra-ldap]]
      config:
        log_level: info
        authentik_host: https://sso.melotic.dev
        object_naming_template: ak-outpost-%(name)s
        kubernetes_json_patches:
          service:
            - op: add
              path: /metadata/annotations
              value:
                external-dns.alpha.kubernetes.io/hostname: ghidra-ldap.melotic.dev
            - op: add
              path: /spec/loadBalancerSourceRanges
              value:
                - 10.42.0.0/16
                - 10.60.0.0/16
        kubernetes_namespace: default
        kubernetes_replicas: 1
        kubernetes_service_type: LoadBalancer
