---
# yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
version: 1
metadata:
  name: slskd removal
entries:
  - model: authentik_core.application
    state: absent
    identifiers:
      slug: slskd

  - model: authentik_providers_proxy.proxyprovider
    state: absent
    identifiers:
      name: slskd
