---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/v1/namespace.json
apiVersion: v1
kind: Namespace
metadata:
  name: not-used
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
