---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/postgresql.cnpg.io/databaserole_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: crowdsec
spec:
  name: crowdsec
  ensure: present
  login: true
  passwordSecret:
    name: postgres-user-crowdsec
  cluster:
    name: postgres-cluster
