---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-user-paperless
spec:
  refreshPolicy: Periodic
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: postgres-user-paperless
    creationPolicy: Owner
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        user: paperless
        username: paperless
        password: "{{ .password }}"
  dataFrom:
    - extract:
        key: paperless-postgres
