---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/postgresql.cnpg.io/databaserole_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: renovate
spec:
  name: renovate
  ensure: present
  login: true
  passwordSecret:
    name: postgres-user-renovate
  cluster:
    name: postgres-cluster
