---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: azure-mirror
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: azure-mirror-creds
    template:
      data:
        AZURE_STORAGE_ACCOUNT: "{{ .AZURE_ACCOUNT_NAME }}"
        AZURE_STORAGE_SAS_TOKEN: "{{ .AZURE_SAS_TOKEN }}"
  dataFrom:
    - extract:
        key: nas-backup-azure
