---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-azure-backup
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  refreshInterval: 5m
  target:
    name: gitlab-azure-backup
    template:
      engineVersion: v2
      type: Opaque
      data:
        config: |
          azure_storage_account_name: {{ .AZURE_STORAGE_ACCOUNT }}
          azure_storage_access_key: {{ .AZURE_STORAGE_ACCESS_KEY }}
          azure_storage_domain: blob.core.windows.net
  data:
    - secretKey: AZURE_STORAGE_ACCOUNT
      remoteRef:
        key: gitlab-azure-backup
        property: AZURE_STORAGE_ACCOUNT
    - secretKey: AZURE_STORAGE_ACCESS_KEY
      remoteRef:
        key: gitlab-azure-backup
        property: AZURE_STORAGE_ACCESS_KEY
