---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-initial-root-password
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  refreshInterval: 5m
  target:
    name: gitlab-initial-root-password
  data:
    - secretKey: password
      remoteRef:
        key: gitlab-initial-root-password
        property: password
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-minio-creds
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  refreshInterval: 5m
  target:
    name: gitlab-minio-creds
    template:
      type: Opaque
      data:
        MINIO_ROOT_USER: "{{ .root_user }}"
        MINIO_ROOT_PASSWORD: "{{ .root_password }}"
        accesskey: "{{ .access_key }}"
        secretkey: "{{ .secret_key }}"
  dataFrom:
    - extract:
        key: gitlab-minio
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-object-store-connection
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  refreshInterval: 5m
  target:
    name: gitlab-object-store-connection
    template:
      type: Opaque
      data:
        connection: |
          provider: AWS
          region: us-east-1
          aws_access_key_id: {{ .access_key | quote }}
          aws_secret_access_key: {{ .secret_key | quote }}
          endpoint: 'http://gitlab-minio.gitlab.svc.cluster.local:9000'
          path_style: true
        s3cfg: |
          [default]
          access_key = {{ .access_key }}
          secret_key = {{ .secret_key }}
          host_base = gitlab-minio.gitlab.svc.cluster.local:9000
          host_bucket = gitlab-minio.gitlab.svc.cluster.local:9000/%(bucket)
          use_https = False
          signature_v2 = False
  dataFrom:
    - extract:
        key: gitlab-minio
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-oidc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  refreshInterval: 5m
  target:
    name: gitlab-oidc
    template:
      type: Opaque
      data:
        provider: |
          name: openid_connect
          label: Authentik
          args:
            name: openid_connect
            scope: [openid, profile, email]
            response_type: code
            issuer: https://sso.melotic.dev/application/o/gitlab/
            discovery: true
            client_auth_method: query
            uid_field: preferred_username
            client_options:
              identifier: {{ .client_id | quote }}
              secret: {{ .client_secret | quote }}
              redirect_uri: https://gitlab.melotic.dev/users/auth/openid_connect/callback
  data:
    - secretKey: client_id
      remoteRef:
        key: authentik-oidc
        property: gitlab_client_id
    - secretKey: client_secret
      remoteRef:
        key: authentik-oidc
        property: gitlab_client_secret
