---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/v1/serviceaccount.json
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-rgw-secret-reader
automountServiceAccountToken: false
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/rbac.authorization.k8s.io/role_v1.json
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitlab-rgw-secret-reader
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["rook-ceph-object-user-gitlab-rgw-gitlab-rgw"]
    verbs: ["get"]
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/rbac.authorization.k8s.io/rolebinding_v1.json
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitlab-rgw-secret-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gitlab-rgw-secret-reader
subjects:
  - kind: ServiceAccount
    name: gitlab-rgw-secret-reader
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/secretstore_v1.json
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gitlab-rgw
spec:
  provider:
    kubernetes:
      remoteNamespace: gitlab
      server:
        url: https://kubernetes.default.svc
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: gitlab-rgw-secret-reader
