---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-runner-cache-credentials
spec:
  secretStoreRef:
    kind: SecretStore
    name: gitlab-runner-cache-rgw
  refreshInterval: 5m
  target:
    name: gitlab-runner-cache-credentials
    template:
      type: Opaque
      data:
        accesskey: "{{ .AccessKey }}"
        secretkey: "{{ .SecretKey }}"
  data:
    - secretKey: AccessKey
      remoteRef:
        key: gitlab-runner-cache
        property: AWS_ACCESS_KEY_ID
    - secretKey: SecretKey
      remoteRef:
        key: gitlab-runner-cache
        property: AWS_SECRET_ACCESS_KEY
