---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app librechat
  namespace: &namespace default
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: authentik
      namespace: default
    - name: tailscale-policy
      namespace: network
    - name: librechat-images
      namespace: default
    - name: librechat-meilisearch
      namespace: default
    - name: librechat-mongodb
      namespace: default
  path: ./kubernetes/apps/default/librechat/app
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  wait: false
