---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: librechat
  namespace: default
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: librechat
  dependsOn:
    - name: authentik
      namespace: default
    - name: tailscale-policy
      namespace: network
    - name: librechat-images
      namespace: default
    - name: librechat-meilisearch
      namespace: default
    - name: librechat-mongodb
      namespace: default
  path: ./kubernetes/apps/default/librechat/app
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
  wait: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: librechat-images
  namespace: default
spec:
  interval: 1h
  prune: true
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: kopiur-repository
      namespace: kopiur-system
  path: ./kubernetes/components/kopiur/backup
  postBuild:
    substitute:
      APP: librechat-images
      KOPIUR_CAPACITY: 10Gi
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
  wait: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: librechat-meilisearch
  namespace: default
spec:
  interval: 1h
  prune: true
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: kopiur-repository
      namespace: kopiur-system
  path: ./kubernetes/components/kopiur/backup
  postBuild:
    substitute:
      APP: librechat-meilisearch
      KOPIUR_CAPACITY: 5Gi
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
  wait: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: librechat-mongodb
  namespace: default
spec:
  interval: 1h
  prune: true
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: kopiur-repository
      namespace: kopiur-system
  path: ./kubernetes/components/kopiur/backup
  postBuild:
    substitute:
      APP: librechat-mongodb
      KOPIUR_CAPACITY: 8Gi
      KOPIUR_PUID: '1001'
      KOPIUR_PGID: '1001'
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
  wait: false
