# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:N6H2YBx9j8YVr5l2zQ4IaQqbgLaRZHu1eHjkATfIKcQv+rPk2jPxQg==,iv:5xH+SwEw6r8D4SrXpMGV6/qNJs5lFFn5oE68Wg2wwDQ=,tag:K5moe+MH2CT9l/rz7uDn4w==,type:str]
sops:
  age:
    - recipient: age1swl8rf4aqksyqrwuyum0ny7vq5a7mtna0n79umsrw7lkrh2859zqsx0mpk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArSExyWGRic2hUY0ZwNXBo
        RnpRMlp5NHZTak5DQUtxc2lGUStTNzhxMERBCktRVnhNVklDOGhib0dVYVF0NWJk
        WU5Qb3Urc2xUYU1zM1ZvL2MvU0NuYWcKLS0tIFVQUG5abTFQRDQ2clV3VHR6VC9O
        Q0JubXBET2hvZ0RibXBpNXk3dzN4cU0KmAvbAmrLK96ABywyiYwyTUqJEbOptLyI
        seG7UxZ3f3QWDrnYwrqLCDXPkogmQxBkHU7r/237rvFjd6AQIasC3Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-14T04:09:53Z"
  mac: ENC[AES256_GCM,data:tu4Gs61ORIVETvx1hLahY9cCF8qamqXwCsBmSXNoxB32SuH4hK/AYpScaCQOqhSkAHBj1XUTuDwEr7Ivpv6wkz91SV9dtkWYxqMyltlWW0zzEvMWP/NLulgMpPaYlyHTp+y+c6Z3WKtBQ0dMvP2hEzidxzbthYDDXdf1YYnZ0i4=,iv:JPtzkr3Iy6I4E5MiP4168m/43fmh8GWfj58MZYtiZJk=,tag:5zXEjgl4j52tsgX3WZCgIg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.1
