# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:wu6kYAbPcbxP54/w+hC7AdiCTjtGXJn+Zf/HpvwQXqFaoVyOdoAdEA==,iv:Zl4K9gdZtdl52EKYKyicUTVqYPO5P+o5njmD3J8nGZ4=,tag:uS5/1KD0jNonBWQUDW6Tkw==,type:str]
sops:
  age:
    - recipient: age1swl8rf4aqksyqrwuyum0ny7vq5a7mtna0n79umsrw7lkrh2859zqsx0mpk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKeHFGVklsYnVnaWlvdGN2
        eS8weW9YSU9yampyVi9LOFJFL3JFMmwyWlNjCkhMWmxQaUxqcXpCNVlhRDNCejdC
        SmZsOWExUHVuanNZOWJOWlV5SGlQV1kKLS0tIEU3YjJCK3FEQ0tDVVp0cDFTMzlM
        R0NZVTRoZUMyVE44QmdEMER4MUNEOTQKlTC0yANTrQyP9Y8AwpVjJyB7vZ4YFBCt
        BiI6/gaw6g0scQqmNX4+BhPrTkUdugVKmSBV2rk11HuTQATD3Z4awA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-14T02:34:39Z"
  mac: ENC[AES256_GCM,data:3AlBZgRjC5HP1EATfdfPGkGLDs/WpFNTqwlfFH2l621oTjkED6lnThrxM6Mw9zPP9Xb7vBwhP8hz6DYZTpfafU/CZJ7ha/QJ3iO5HplDw8TRt60JX8jGhkbe/Mk00N8SIDoV5LYuKFZegze0aeOXF3ZmwMS3WcIpDm0FPlVkokU=,iv:viR3l6eF+ht7L2PmwyWR8j+601Lekj6vkWzwr2v/nPI=,tag:Ble/Kwgd2OzqptpdYhC2EA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.1
