---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/monitoring.coreos.com/alertmanagerconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager
spec:
  route:
    receiver: blackhole
    groupBy: ["alertname", "job"]
    groupWait: 1m
    groupInterval: 10m
    repeatInterval: 12h
    routes:
      - receiver: grafana-irm
        matchers:
          - name: severity
            value: critical
            matchType: =
        continue: true
      - receiver: grafana-irm
        matchers:
          - name: alertname
            value: KubePodCrashLooping|KubeNodeNotReady
            matchType: =~
        continue: true
      - receiver: grafana-irm
        matchers:
          - name: alertname
            value: KubeContainerWaiting
            matchType: =
          - name: reason
            value: ImagePullBackOff|ErrImagePull|InvalidImageName|CreateContainerConfigError
            matchType: =~
        continue: true
      - receiver: grafana-irm
        matchers:
          - name: tier
            value: security
            matchType: =
        continue: true
      - receiver: webhook
        matchers:
          - name: severity
            value: critical|warning|error
            matchType: =~
  inhibitRules:
    - equal: ["namespace", "alertname"]
      sourceMatch:
        - name: severity
          value: critical
          matchType: =
      targetMatch:
        - name: severity
          value: warning|info
          matchType: =~
    - equal: ["namespace", "pod"]
      sourceMatch:
        - name: alertname
          value: OomKilled
          matchType: =
      targetMatch:
        - name: alertname
          value: KubePodCrashLooping
          matchType: =
  receivers:
    - name: blackhole
    - name: grafana-irm
      webhookConfigs:
        - sendResolved: true
          urlSecret:
            name: alertmanager-webhook-secret
            key: GRAFANA_IRM_ENDPOINT
    - name: webhook
      webhookConfigs:
        - sendResolved: true
          urlSecret:
            name: alertmanager-webhook-secret
            key: WEBHOOK_URL
          httpConfig:
            authorization:
              type: Bearer
              credentials:
                name: alertmanager-webhook-secret
                key: WEBHOOK_TOKEN
            tlsConfig:
              serverName: disco-ninja.tail88eb4.ts.net
