---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/alertmanagerconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager
spec:
  route:
    groupBy: ["alertname", "job"]
    groupInterval: 10m
    groupWait: 1m
    receiver: irm
    repeatInterval: 12h
    routes:
      - receiver: "null"
        matchers:
          - name: alertname
            value: InfoInhibitor
            matchType: =
      - receiver: heartbeat
        groupInterval: 5m
        groupWait: 0s
        repeatInterval: 5m
        matchers:
          - name: alertname
            value: Watchdog
            matchType: =
      - receiver: irm
        matchers:
          - name: severity
            value: critical
            matchType: =
  inhibitRules:
    - equal: ["alertname", "namespace"]
      sourceMatch:
        - name: severity
          value: critical
          matchType: =
      targetMatch:
        - name: severity
          value: warning
          matchType: =
  receivers:
    - name: "null"
    - name: heartbeat
      webhookConfigs:
        - urlSecret:
            name: &secret alertmanager-secret
            key: grafana-irm-heartbeat
    - name: irm
      webhookConfigs:
        - sendResolved: true
          maxAlerts: 100
          urlSecret:
            name: *secret
            key: grafana-irm-url
