---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  chartRef:
    kind: OCIRepository
    name: kube-prometheus-stack
  interval: 1h
  values:
    cleanPrometheusOperatorObjectNames: true
    crds:
      enabled: false
      upgradeJob:
        enabled: false
    grafana:
      enabled: false
      forceDeployDashboards: true
      operator:
        dashboardsConfigMapRefEnabled: true
        folder: General
        matchLabels:
          dashboards: grafana
    alertmanager:
      route:
        main:
          enabled: true
          hostnames:
            - alertmanager.melotic.dev
          parentRefs:
            - name: envoy-internal
              namespace: network
              sectionName: https
      alertmanagerSpec:
        alertmanagerConfiguration:
          name: alertmanager
        externalUrl: https://alertmanager.melotic.dev
        resources:
          requests:
            cpu: 25m
            memory: 128Mi
          limits:
            memory: 256Mi
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: ceph-block
              resources:
                requests:
                  storage: 1Gi
    prometheus:
      route:
        main:
          enabled: true
          hostnames:
            - prometheus.melotic.dev
          parentRefs:
            - name: envoy-internal
              namespace: network
              sectionName: https
      prometheusSpec:
        externalUrl: https://prometheus.melotic.dev
        evaluationInterval: 1m
        scrapeInterval: 1m
        podMonitorSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        ruleSelectorNilUsesHelmValues: false
        scrapeConfigSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        retention: 31d
        retentionSize: 40GB
        resources:
          requests:
            cpu: 250m
            memory: 1Gi
          limits:
            memory: 4Gi
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: ceph-block
              resources:
                requests:
                  storage: 50Gi
    prometheusOperator:
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          memory: 256Mi
      prometheusConfigReloader:
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            memory: 64Mi
    nodeExporter:
      enabled: false
    kubeStateMetrics:
      enabled: false
    kubeProxy:
      enabled: false
    kubeEtcd:
      service:
        port: 2381
        targetPort: 2381
        selector:
          component: kube-apiserver
      serviceMonitor:
        endpoints:
          - port: http-metrics
            scheme: http
            path: /metrics
            metricRelabelings:
              - action: drop
                regex: (etcd_request|apiserver_request_slo|apiserver_request_sli|apiserver_request)_duration_seconds_bucket;(0\.15|0\.2|0\.3|0\.35|0\.4|0\.45|0\.6|0\.7|0\.8|0\.9|1\.25|1\.5|1\.75|2|3|3\.5|4|4\.5|6|7|8|9|15|20|40|45|50)(\.0)?
                sourceLabels:
                  - __name__
                  - le
    kubeApiServer:
      serviceMonitor:
        metricRelabelings:
          - action: drop
            regex: (etcd_request|apiserver_request_slo|apiserver_request_sli|apiserver_request)_duration_seconds_bucket;(0\.15|0\.2|0\.3|0\.35|0\.4|0\.45|0\.6|0\.7|0\.8|0\.9|1\.25|1\.5|1\.75|2|3|3\.5|4|4\.5|6|7|8|9|15|20|40|45|50)(\.0)?
            sourceLabels:
              - __name__
              - le
          - action: drop
            regex: apiserver_request_body_size_bytes_bucket|apiserver_watch_list_duration_seconds_bucket|apiserver_watch_cache_read_wait_seconds_bucket|apiserver_response_sizes_bucket|apiserver_watch_events_sizes_bucket|workqueue_work_duration_seconds_bucket
            sourceLabels:
              - __name__
    kubeScheduler:
      serviceMonitor:
        metricRelabelings:
          - action: drop
            regex: scheduler_plugin_execution_duration_seconds_bucket|workqueue_work_duration_seconds_bucket
            sourceLabels:
              - __name__
    kubeControllerManager:
      serviceMonitor:
        metricRelabelings:
          - action: drop
            regex: workqueue_work_duration_seconds_bucket
            sourceLabels:
              - __name__
