---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./alertmanagerconfig.yaml
  - ./helmrelease.yaml
  - ./secrets.sops.yaml
configMapGenerator:
  - name: flux-ksm-config
    files:
      - ./helm/kube-state-metrics-config.yaml
configurations:
  - ./helm/kustomizeconfig.yaml
