---
originRequest:
  http2Origin: true
  keepAliveTimeout: 3600s
  originServerName: "external.melotic.dev"
  tcpKeepAlive: 7200s

ingress:
  - hostname: "melotic.dev"
    service: &svc https://envoy-external.network.svc.cluster.local
  - hostname: "*.melotic.dev"
    service: *svc
  - service: http_status:404
