---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: policy-reporter
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: policy-reporter-oidc
    creationPolicy: Owner
    template:
      data:
        clientId: "{{ .authentik_policy_reporter_client_id }}"
        clientSecret: "{{ .authentik_policy_reporter_client_secret }}"
  dataFrom:
    - extract:
        key: authentik-oidc
      rewrite:
        - regexp:
            source: "(.*)"
            target: "authentik_$1"
