---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/serviceaccount.json
apiVersion: v1
kind: ServiceAccount
metadata:
  name: plex-trinity-return
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: plex-trinity-return-node-reader
rules:
  - apiGroups: [""]
    resources: [nodes]
    verbs: [get, list]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: plex-trinity-return-node-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: plex-trinity-return-node-reader
subjects:
  - kind: ServiceAccount
    name: plex-trinity-return
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: plex-trinity-return
  namespace: default
rules:
  - apiGroups: [""]
    resources: [pods]
    verbs: [get, list, delete]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: plex-trinity-return
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: plex-trinity-return
subjects:
  - kind: ServiceAccount
    name: plex-trinity-return
    namespace: default
