---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-webui
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: open-webui-secret
    template:
      data:
        WEBUI_SECRET_KEY: "{{ .WEBUI_SECRET_KEY }}"
        OAUTH_CLIENT_ID: "{{ .open_webui_client_id }}"
        OAUTH_CLIENT_SECRET: "{{ .open_webui_client_secret }}"
  dataFrom:
    - extract:
        key: open-webui
    - extract:
        key: authentik-oidc
