# yaml-language-server: $schema=https://homelab-schemas-epg.pages.dev/dragonflydb.io/dragonfly_v1alpha1.json
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: &app dragonfly
spec:
  replicas: 3
  image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.30.1@sha256:2a5c3606df45b8d171a9b46cec56a246b773e53def973c763d52b044534b76ed
  args:
    - --cluster_mode=emulated
    - --lock_on_hashtags
    # For immich
    - --default_lua_flags=allow-undeclared-keys
    - --maxmemory=$(MAX_MEMORY)Mi
    - --proactor_threads=2
  env:
    - name: MAX_MEMORY
      valueFrom:
        resourceFieldRef:
          resource: limits.memory
          divisor: 1Mi
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 512Mi
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: *app
