---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app victoria-metrics-k8s-stack
  namespace: &namespace monitoring
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 1h
  path: ./kubernetes/apps/monitoring/victoria-metrics-k8s-stack/app
  prune: true
  postBuild:
    substitute:
      AUTH_POLICY_NAME: victoria-metrics-auth
      AUTH_HTTPROUTE: vmsingle-vm-kube-stack
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  wait: false
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: victoria-metrics-alertmanager-auth
  namespace: &namespace monitoring
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: victoria-metrics-k8s-stack
  dependsOn:
    - name: victoria-metrics-k8s-stack
  interval: 1h
  path: ./kubernetes/apps/monitoring/victoria-metrics-k8s-stack/alertmanager-auth
  prune: true
  postBuild:
    substitute:
      AUTH_POLICY_NAME: alertmanager-auth
      AUTH_HTTPROUTE: vmalertmanager-vm-kube-stack
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  wait: false
