---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flux-operator-oidc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: flux-operator-oidc
    template:
      data:
        client-id: "{{ .flux_operator_client_id }}"
        client-secret: "{{ .flux_operator_client_secret }}"
  dataFrom:
    - extract:
        key: authentik-oidc
