---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: librechat
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: librechat-credentials-env
    template:
      engineVersion: v2
      data:
        CREDS_IV: "{{ .CREDS_IV }}"
        CREDS_KEY: "{{ .CREDS_KEY }}"
        JWT_REFRESH_SECRET: "{{ .JWT_REFRESH_SECRET }}"
        JWT_SECRET: "{{ .JWT_SECRET }}"
        MEILI_MASTER_KEY: "{{ .MEILI_MASTER_KEY }}"
        MONGO_URI: "mongodb://librechat:{{ .MONGODB_PASSWORD }}@librechat-mongodb.default.svc.cluster.local:27017/LibreChat?authSource=LibreChat"
        OPENID_CLIENT_ID: "{{ .librechat_client_id }}"
        OPENID_CLIENT_SECRET: "{{ .librechat_client_secret }}"
        OPENID_SESSION_SECRET: "{{ .OPENID_SESSION_SECRET }}"
        mongodb-passwords: "{{ .MONGODB_PASSWORD }}"
        mongodb-root-password: "{{ .MONGODB_ROOT_PASSWORD }}"
  dataFrom:
    - extract:
        key: librechat
    - extract:
        key: authentik-oidc
