---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: meilisearch
spec:
  chartRef:
    kind: OCIRepository
    name: meilisearch
  interval: 1h
  values:
    controllers:
      meilisearch:
        strategy: Recreate
        containers:
          app:
            image:
              repository: docker.io/getmeili/meilisearch
              tag: v1.50.0@sha256:9694a59df43ee3f54b3fda9c5de381a3ee9852678e3e31cadf37d6bddea7fc1b
            env:
              HOME: /tmp
              MEILI_ENV: production
              MEILI_MASTER_KEY:
                valueFrom:
                  secretKeyRef:
                    name: meilisearch-secret
                    key: MEILI_MASTER_KEY
              MEILI_NO_ANALYTICS: "true"
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 7700
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 2
                  failureThreshold: 6
              readiness: *probe
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                memory: 1Gi
    defaultPodOptions:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    service:
      app:
        controller: meilisearch
        ports:
          http:
            port: *port
    persistence:
      data:
        accessMode: ReadWriteOnce
        size: 5Gi
        storageClass: ceph-block
        globalMounts:
          - path: /meili_data
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
