---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tofu-controller-cloudflare
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cf-tfvars
    template:
      engineVersion: v2
      data:
        cloudflare_api_token: "{{ .CLOUDFLARE_ZT_TOKEN | trim }}"
  dataFrom:
    - extract:
        key: cloudflare
