---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tofu-controller
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: tofu-controller
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      strategy: rollback
  values:
    awsPackage:
      install: false
    image:
      repository: ghcr.io/flux-iac/tofu-controller
      tag: v0.16.4@sha256:7f95e82a29c6f0c49965a1e248f2c1713593053819175dd2624c474b05ef5263
    runner:
      image:
        repository: ghcr.io/flux-iac/tf-runner
        tag: v0.16.4@sha256:fc3af4d9b99f54cc92d4aec51d83117dcf373b79d8ed1dc6f69a4ac154184725
      serviceAccount:
        create: true
        allowedNamespaces:
          - flux-system
          - network
    rbac:
      create: true
    podSecurityContext:
      fsGroup: 1337
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 65532
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault
