---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: cf-access-verify
  namespace: flux-system
spec:
  interval: 10m
  approvePlan: auto
  destroyResourcesOnDeletion: true
  path: ./kubernetes/apps/flux-system/tofu-controller/terraform/cf-verify
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  vars:
    - name: account_id
      value: "31bd6064f8c4bcc23fcb7eb49c171c98"
  varsFrom:
    - kind: Secret
      name: cf-tfvars
