---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/generators.external-secrets.io/clustergenerator_v1alpha1.json
apiVersion: generators.external-secrets.io/v1alpha1
kind: ClusterGenerator
metadata:
  name: pg-password-generator
spec:
  kind: Password
  generator:
    passwordSpec:
      allowRepeat: true
      digits: 5
      length: 42
      noUpper: false
      symbolCharacters: "-_$@"
      symbols: 5
