---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/ocirepository-source-v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: immich
  namespace: default
spec:
  interval: 5m
  ref:
    tag: 0.9.3
  url: oci://ghcr.io/immich-app/immich-charts/immich
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: immich
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    env:
      DB_DATABASE_NAME: immich
      DB_HOSTNAME: cnpg-cluster-rw
      DB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: cnpg-cluster-immich
            key: password
      DB_USERNAME: immich
      DB_VECTOR_EXTENSION: pgvector
      REDIS_HOSTNAME: dragonfly
    image:
      # renovate: datasource=github-releases depName=immich-app/immich
      tag: v1.133.1
    immich:
      # update the config secret instead of this
      configuration: {}
      metrics:
        enabled: true
      persistence:
        library:
          existingClaim: immich-library
    server:
      env:
        IMMICH_CONFIG_FILE: /config/immich-config.yaml
      # manually mount the config as a secret, since it has oauth secrets
      persistence:
        config:
          enabled: true
          name: immich-config
          type: secret
      podAnnotations:
        reloader.stakater.com/auto: "true"