---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
  name: pv-immich-library
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 32Gi
  csi:
    driver: nfs.csi.k8s.io
    volumeAttributes:
      server: 10.60.10.20
      share: /var/nfs/shared
      subdir: photos
    volumeHandle: 10.60.10.20#var/nfs/shared#photos
  mountOptions:
    - vers=3
    - nolock
    - noatime
    - async
    - rsize=131072
    - wsize=131072
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 32Gi
  storageClassName: nfs-csi
  volumeName: pv-immich-library
