---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: postgres
spec:
  interval: 15m
  url: https://cloudnative-pg.github.io/charts
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres
spec:
  interval: 1h
  chart:
    spec:
      chart: cluster
      sourceRef:
        kind: HelmRepository
        name: postgres
      version: 0.6.1
  install:
    remediation:
      retries: -1
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Cluster
              name: postgres-cluster
            patch: |
              apiVersion: postgresql.cnpg.io/v1
              kind: Cluster
              metadata:
                name: postgres-cluster
              spec:
                plugins:
                  - name: barman-cloud.cloudnative-pg.io
                    isWALArchiver: true
                    parameters:
                      barmanObjectName: azure-blob-store
          - target:
              kind: Cluster
              name: postgres-cluster
            patch: |
              - op: test
                path: /spec/externalClusters/0/name
                value: objectStoreRecoveryCluster
              - op: replace
                path: /spec/externalClusters
                value:
                  - name: objectStoreRecoveryCluster
                    plugin:
                      name: barman-cloud.cloudnative-pg.io
                      parameters:
                        barmanObjectName: azure-blob-store
                        serverName: postgres-cluster
  values:
    type: postgresql
    mode: recovery
    version:
      postgresql: "17"
    backups:
      enabled: false
    cluster:
      priorityClassName: cluster-critical
      affinity:
        enablePodAntiAffinity: true
        podAntiAffinityType: required
        topologyKey: kubernetes.io/hostname
      imageCatalogRef:
        kind: ClusterImageCatalog
        name: postgresql-minimal-trixie
      instances: 3
      monitoring:
        enabled: true
        podMonitor:
          enabled: false
        prometheusRule:
          enabled: true
      resources:
        requests:
          cpu: 100m
          memory: 768Mi
        limits:
          memory: 1Gi
      roles:
        - name: app
          ensure: absent
        - name: seerr
          ensure: present
          login: true
          passwordSecret:
            name: postgres-user-seerr
        - name: sonarr
          ensure: present
          login: true
          passwordSecret:
            name: postgres-user-sonarr
        - name: radarr
          ensure: present
          login: true
          passwordSecret:
            name: postgres-user-radarr
        - name: lidarr
          ensure: present
          login: true
          passwordSecret:
            name: postgres-user-lidarr
        - name: prowlarr
          ensure: present
          login: true
          passwordSecret:
            name: postgres-user-prowlarr
        - name: atuin
          ensure: present
          login: true
          passwordSecret:
            name: postgres-user-atuin
        - name: authentik
          ensure: present
          login: true
          passwordSecret:
            name: postgres-user-authentik
        - name: harbor
          ensure: present
          login: true
          passwordSecret:
            name: postgres-user-harbor
        - name: forejo
          ensure: present
          login: true
          passwordSecret:
            name: postgres-user-forejo
        - name: paperless
          ensure: present
          login: true
          passwordSecret:
            name: postgres-user-paperless
        - name: gitlab
          ensure: present
          login: true
          passwordSecret:
            name: postgres-user-gitlab
      storage:
        size: 16Gi
        storageClass: openebs-hostpath
    recovery:
      method: object_store
      clusterName: postgres-cluster
      database: ""
      owner: ""
      provider: azure
      destinationPath: https://sthomeopsbackup.blob.core.windows.net/cnpg-backup/
      secret:
        create: false
        name: cnpg-backup-azure-creds
