---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: postgres
spec:
  interval: 15m
  url: https://cloudnative-pg.github.io/charts
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres
spec:
  interval: 1h
  chart:
    spec:
      chart: cluster
      sourceRef:
        kind: HelmRepository
        name: postgres
      version: 0.9.0
  install:
    remediation:
      retries: -1
  values:
    type: postgresql
    mode: recovery
    version:
      postgresql: "17"
    backups:
      enabled: false
    cluster:
      priorityClassName: cluster-critical
      affinity:
        enablePodAntiAffinity: true
        podAntiAffinityType: required
        topologyKey: kubernetes.io/hostname
      imageCatalogRef:
        kind: ClusterImageCatalog
        name: postgresql-minimal-trixie
      instances: 3
      monitoring:
        enabled: true
        podMonitor:
          enabled: false
        prometheusRule:
          enabled: true
      resources:
        requests:
          cpu: 100m
          memory: 768Mi
        limits:
          memory: 1Gi
      storage:
        size: 16Gi
        storageClass: openebs-hostpath
      postgresql:
        synchronous:
          method: any
          number: 1
          dataDurability: preferred
      plugins:
        - name: barman-cloud.cloudnative-pg.io
          enabled: true
          isWALArchiver: true
          parameters:
            barmanObjectName: azure-blob-store
            #serverName: postgres-cluster-pg18
    recovery:
      method: plugin
      clusterName: postgres-cluster
      database: ""
      owner: ""
      provider: azure
      secret:
        create: false
      objectStore:
        create: false
      pluginConfiguration:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: azure-blob-store
