---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: postgres
spec:
  interval: 15m
  url: https://cloudnative-pg.github.io/charts
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres
spec:
  interval: 1h
  chart:
    spec:
      chart: cluster
      sourceRef:
        kind: HelmRepository
        name: postgres
      version: 0.6.0
  install:
    remediation:
      retries: -1
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Cluster
              name: postgres-cluster
            patch: |
              apiVersion: postgresql.cnpg.io/v1
              kind: Cluster
              metadata:
                name: postgres-cluster
              spec:
                plugins:
                  - name: barman-cloud.cloudnative-pg.io
                    isWALArchiver: true
                    parameters:
                      barmanObjectName: azure-blob-store
  values:
    type: postgresql
    mode: recovery
    version:
      postgresql: "17"
    backups:
      enabled: false
    cluster:
      priorityClassName: cluster-critical
      affinity:
        topologyKey: kubernetes.io/hostname
      imageCatalogRef:
        kind: ClusterImageCatalog
        name: postgresql-minimal-trixie
      instances: 3
      monitoring:
        enabled: true
      resources:
        requests:
          cpu: 100m
          memory: 768Mi
        limits:
          memory: 1Gi
      roles:
        - name: app
          ensure: present
          login: true
          inRoles:
            - pg_monitor
            - pg_signal_backend
          passwordSecret:
            name: postgres-cluster-app
      storage:
        size: 16Gi
        storageClass: longhorn-cnpg-strict-local
    recovery:
      method: pg_basebackup
      pgBaseBackup:
        database: app
        owner: app
        secretName: psql-apps-cluster-app
        source:
          host: psql-apps-cluster-rw.default.svc.cluster.local
          port: 5432
          username: streaming_replica
          database: postgres
          sslMode: verify-full
          sslRootCertSecret:
            name: psql-apps-cluster-ca
            key: ca.crt
          sslCertSecret:
            name: psql-apps-cluster-replication
            key: tls.crt
          sslKeySecret:
            name: psql-apps-cluster-replication
            key: tls.key
