---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./databases/app.yaml
  - ./databases/atuin.yaml
  - ./databases/authentik.yaml
  - ./databases/crowdsec.yaml
  - ./databases/firefly.yaml
  - ./databases/harbor.yaml
  - ./databases/gitlab.yaml
  - ./databases/miniflux.yaml
  - ./databases/openwebui.yaml
  - ./databases/paperless.yaml
  - ./databases/prowlarr.yaml
  - ./databases/radarr.yaml
  - ./databases/renovate.yaml
  - ./databases/seerr.yaml
  - ./databases/sonarr.yaml
  - ./externalsecret-backup.yaml
  - ./helmrelease.yaml
  - ./objectstore.yaml
  - ./scheduledbackup.yaml
  - ./monitoring/cluster-podmonitor.yaml
  - ./monitoring/pooler-podmonitor.yaml
  - ./pooler/pooler-rw.yaml
  - ./prometheusrule-backup.yaml
  - ./roles/atuin.yaml
  - ./secrets/atuin.yaml
  - ./roles/authentik.yaml
  - ./secrets/authentik.yaml
  - ./roles/crowdsec.yaml
  - ./secrets/crowdsec.yaml
  - ./roles/firefly.yaml
  - ./secrets/firefly.yaml
  - ./roles/gitlab.yaml
  - ./secrets/gitlab.yaml
  - ./roles/harbor.yaml
  - ./secrets/harbor.yaml
  - ./roles/miniflux.yaml
  - ./secrets/miniflux.yaml
  - ./roles/openwebui.yaml
  - ./secrets/openwebui.yaml
  - ./roles/paperless.yaml
  - ./secrets/paperless.yaml
  - ./roles/prowlarr.yaml
  - ./secrets/prowlarr.yaml
  - ./roles/radarr.yaml
  - ./secrets/radarr.yaml
  - ./roles/renovate.yaml
  - ./secrets/renovate.yaml
  - ./roles/seerr.yaml
  - ./secrets/seerr.yaml
  - ./roles/sonarr.yaml
  - ./secrets/sonarr.yaml
