---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./databases/app.yaml
  - ./databases/atuin.yaml
  - ./databases/authentik.yaml
  - ./databases/harbor.yaml
  - ./databases/gitlab.yaml
  - ./databases/lidarr.yaml
  - ./databases/linkwarden.yaml
  - ./databases/paperless.yaml
  - ./databases/prowlarr.yaml
  - ./databases/radarr.yaml
  - ./databases/seerr.yaml
  - ./databases/sonarr.yaml
  - ./externalsecret-backup.yaml
  - ./helmrelease.yaml
  - ./objectstore.yaml
  - ./scheduledbackup.yaml
  - ./monitoring/cluster-podmonitor.yaml
  - ./monitoring/pooler-podmonitor.yaml
  - ./pooler/pooler-rw.yaml
  - ./prometheusrule-backup.yaml
  - ./roles/atuin.yaml
  - ./roles/authentik.yaml
  - ./roles/gitlab.yaml
  - ./roles/harbor.yaml
  - ./roles/lidarr.yaml
  - ./roles/linkwarden.yaml
  - ./roles/paperless.yaml
  - ./roles/prowlarr.yaml
  - ./roles/radarr.yaml
  - ./roles/seerr.yaml
  - ./roles/sonarr.yaml
