# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-secret
stringData:
  github-status-token-secret: ENC[AES256_GCM,data:YoSMZLsRT44FDaQDe8r1UMTB0XLM0dFeTskpgdju2g/VtADudw4XRbdIykP0zrzGzY+B8FJ8GIgJuvlW8d9pbGKtPY8rquXdQqnNx+vKlyrCu29n+lop6+Z0MnfK,iv:CWBlmF9b5EYNFPmgWxA/BTPV3/RI7pjjWgAkwGdeA14=,tag:menoDB8yznZXfLDL8ykkWA==,type:str]
sops:
  age:
    - recipient: age1swl8rf4aqksyqrwuyum0ny7vq5a7mtna0n79umsrw7lkrh2859zqsx0mpk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArSExyWGRic2hUY0ZwNXBo
        RnpRMlp5NHZTak5DQUtxc2lGUStTNzhxMERBCktRVnhNVklDOGhib0dVYVF0NWJk
        WU5Qb3Urc2xUYU1zM1ZvL2MvU0NuYWcKLS0tIFVQUG5abTFQRDQ2clV3VHR6VC9O
        Q0JubXBET2hvZ0RibXBpNXk3dzN4cU0KmAvbAmrLK96ABywyiYwyTUqJEbOptLyI
        seG7UxZ3f3QWDrnYwrqLCDXPkogmQxBkHU7r/237rvFjd6AQIasC3Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-16T01:27:46Z"
  mac: ENC[AES256_GCM,data:nASn+ctHAfDk4gRUQHcek+cEjykviHqd0Kwkt5wtEoEcUkUfcGUEotumoPaU2mcAsGmRdPvP5Dn78cL9rgD1lv0sMALtVPK70aXDew5ucqkTiJdW7Sli1j0hjJ+CRXqxeawmvC/KZ2oriiQxS0Y0sCavGJC3HYsv7AA7fcs2XbQ=,iv:ykTGOtS9pb1EQ2cgn0zGmkTjhjHKn7Ngvg/IGphRtJI=,tag:C3V9uNnTHdHUo5sqq59U/A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.1
