# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: github-status-token
stringData:
    token: ENC[AES256_GCM,data:kmkPodHoKdUkf8m4oJLYkPnH1Ua0729AVxzlr+1Z3OtjKm+qCpJs1qNmqzhlvQFwSZN6mKQjaZ5/yoZOj6lemkKx4z5tLvYULTDZCbf7HxSbQzMR6x49gsDrkhEe,iv:EJcKN0WQsaa48zcOGWuFJ0kTrulZR3T1uuFYkcNUY6E=,tag:lR2Qv+EeBRfBNNn34tm8Bw==,type:str]
sops:
    age:
        - recipient: age1swl8rf4aqksyqrwuyum0ny7vq5a7mtna0n79umsrw7lkrh2859zqsx0mpk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArSExyWGRic2hUY0ZwNXBo
            RnpRMlp5NHZTak5DQUtxc2lGUStTNzhxMERBCktRVnhNVklDOGhib0dVYVF0NWJk
            WU5Qb3Urc2xUYU1zM1ZvL2MvU0NuYWcKLS0tIFVQUG5abTFQRDQ2clV3VHR6VC9O
            Q0JubXBET2hvZ0RibXBpNXk3dzN4cU0KmAvbAmrLK96ABywyiYwyTUqJEbOptLyI
            seG7UxZ3f3QWDrnYwrqLCDXPkogmQxBkHU7r/237rvFjd6AQIasC3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-16T01:44:20Z"
    mac: ENC[AES256_GCM,data:RZQoxERdPK9kmjW/80LYGLmxPxvEX0eOOT65ynMCpAoiWcgZjKnqJHIzTe7k5VFICxflWLBMRT7j90bL2I8kEWKC7FpCApk/WA/R6AEc6HM5PLdj+1lhJCh6/Y1sT9q9nPZMBTScG9D5IJVVCL+cUeoD2zVn7ZVsHXb+Ps21xeA=,iv:To8gkkeU+7RvWG3O0HuVQf13NhmtAGS0vDhBiKPJTK4=,tag:AZOwqq/19DGqqGH2bNPPaw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.1
