---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./externalsecret-prometheus.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  - ./prometheusrule.yaml
  - ./servicemonitor.yaml
configMapGenerator:
  - name: home-assistant-config
    files:
      - config/configuration.yaml
  - name: home-assistant-packages
    files:
      - config/packages/hvac_savings.yaml
configurations:
  - kustomizeconfig.yaml
