---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./grafana.yaml
  - ./grafanadatasource.yaml
  - ./servicemonitor.yaml
  - ./grafanadashboards/external-dns.yaml
  - ./grafanadashboards/kubernetes-api-server.yaml
  - ./grafanadashboards/kubernetes-coredns.yaml
  - ./grafanadashboards/kubernetes-global.yaml
  - ./grafanadashboards/kubernetes-namespaces.yaml
  - ./grafanadashboards/kubernetes-nodes.yaml
  - ./grafanadashboards/kubernetes-pods.yaml
  - ./grafanadashboards/kubernetes-volumes.yaml
  - ./grafanadashboards/node-exporter-full.yaml
  - ./grafanadashboards/vm-stack.yaml
