---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-logs
spec:
  chartRef:
    kind: OCIRepository
    name: victoria-logs
  interval: 1h
  values:
    fullnameOverride: victoria-logs
    server:
      image:
        registry: docker.io
      persistentVolume:
        enabled: true
        storageClassName: ceph-block
        size: 20Gi
      retentionPeriod: 30d
      extraArgs:
        defaultMsgValue: structured log record
      route:
        enabled: false
      serviceMonitor:
        enabled: true
    dashboards:
      enabled: true
      grafanaOperator:
        enabled: true
        spec:
          instanceSelector:
            matchLabels:
              dashboards: grafana
          allowCrossNamespaceImport: true
          folder: General
