apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  IPV6_PREFIX: ENC[AES256_GCM,data:zjj89guqERj2F/sCdPSLydqYaA==,iv:FhSHgYGg9WB7M1PS+O8nRYqkp9SgtekYxkI1DHDxTew=,tag:N60tqGaIjn9smdp+vmn0Zg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrTWw0cURzeFZSbi9EUDcy
        ZjB5ekhOSThBdmJKaE9MQlVIbjFhUFJ6cDA0CjU3RUlKLy83U0E4T3NMUWhjRXhZ
        b0ZOM1haRXBIVm4rNzFEbDNMKzg5ZmMKLS0tIEppRnphc0o4TzN4cG95S0xUckZ5
        RWVTdTVhenQ3WDAxaC9DT1Z3VjlQa0kKxEW1MGB2PBzx/4gSA/DjrEq46pcE1aPW
        Fo3gkyRXL3ApIuJLr+f5PhsT9rgI4v0JcKEiZdVXxDGH0og8dDmnug==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1d8dtvf39qwejljcn0jj7f29xtlnuav9sagfwy76g2asc0d4zjpqsu0s3pd
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-14T18:25:25Z"
  mac: ENC[AES256_GCM,data:e9c1nZIB5G6l0OzMwAeZl++JZa24k3zWe9ez7ibWzZ6V4oF6FRuEPGEpZBCMtODzGXzixOtyfdrC2ZJ8SsibK1UEox1bj4sIB5a8oomAWzHXw4RRIVMNdr5b4i4Ge+4hqjMllWN0LPhelOv9mxIFPR2VycQxBSSq6fVKgxvursA=,iv:j+zmANK+l84HpFlQqvjG9vmn/8IQvoRFOaxbuZZr9a4=,tag:XyKsNus1yfUEYTS2JzclEw==,type:str]
  mac_only_encrypted: true
  version: 3.11.0
