apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  IPV6_BGP_PEER: ENC[AES256_GCM,data:YPMUypY/PEJ6BU1599fubT/RpQ53uw==,iv:+zGaigN98r4+zo6pVU/nHmkTCcIMc5trF95W5L129p8=,tag:GPgcQGuw+12NbJirqUz0QA==,type:str]
  IPV6_LB_POOL: ENC[AES256_GCM,data:RlBb1vxgzszLghgw2kw4pzhC/YWdno0ArpAOWg==,iv:PzEOt9LdQiG0F5+J/uaiMkXx3AImCP0iGDHJLq7/Olo=,tag:gjR99VzyqaLkMnF8fLfEiQ==,type:str]
  IPV6_PREFIX: ENC[AES256_GCM,data:JTqKIgueQZRFHfiQTMR4ObvLcw==,iv:aQGYDdKi7vn0hJEHK0VkQpGOmtA73Dr/+llS7TehOsk=,tag:HM2b4xsGuLlJudSI+KYT3A==,type:str]
  SECRET_DOMAIN: ENC[AES256_GCM,data:he8srsHb4ULGRZk=,iv:7LN0v8RM2JSx3DOBr8HjAItbplPlU58NB/2EMNV5YDo=,tag:xsjXqMqZmn1kBPEufvvwdA==,type:str]
sops:
  age:
    - recipient: age1d8dtvf39qwejljcn0jj7f29xtlnuav9sagfwy76g2asc0d4zjpqsu0s3pd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPOU9FN2dUalhkdTMyOFlH
        N0M0Y0huQW5GV1BIVEFVSTVJUmhXSWQ3eldvCkYwU3YzWmZKYzc2UXorOHZEcUVv
        a3J4VHRwZTExVVVYc3B5c1N6SmhsTVUKLS0tIHlaV1FsRzhKZXFBaFhSazNuR2Nt
        VGJXUXN2bTdwZUN0dzNyMDZXY05TKzAKaMkmcqJoRu5AAb56BWxmJhZpUrxTTwQz
        R2sJ0TaCGOX/QbZU1qxrNm8io1uZJ08IXW6jQLjoMUACML6UeJMHvQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-16T15:03:41Z"
  mac: ENC[AES256_GCM,data:iEiEzB59uMPxAErO0VlmvoHcxnCkOr3NC7nG2dKyMSqMHtCQGvXFfTN6R4zE2aIl4U9KoCxyFMIPTiXu0JyCIiYRaDUHDU0jvp2przUDwzM0KjPXZmCpPGk0iPOlv/SPU8g6qI1/MyUExmbiWDW/2GFNRITfMxGMpCacMg5t3iQ=,iv:gyCI5KgSOCG4vTq7V0qIc9FRN6GtYQQuLRCr//9ErOU=,tag:hrXslc7eBo50qe3DrFxGEg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
