apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  IPV6_PREFIX: ENC[AES256_GCM,data:zjj89guqERj2F/sCdPSLydqYaA==,iv:FhSHgYGg9WB7M1PS+O8nRYqkp9SgtekYxkI1DHDxTew=,tag:N60tqGaIjn9smdp+vmn0Zg==,type:str]
  SECRET_DOMAIN: ENC[AES256_GCM,data:Bfnw8Hl1DkjenqU=,iv:mwVItn/O1S9VHSJ2w806xLBVVdwQBFn27xamg0LWg8c=,tag:BHt9Za5zZP4reyWg/xbIxA==,type:str]
sops:
  age:
    - recipient: age1d8dtvf39qwejljcn0jj7f29xtlnuav9sagfwy76g2asc0d4zjpqsu0s3pd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrTWw0cURzeFZSbi9EUDcy
        ZjB5ekhOSThBdmJKaE9MQlVIbjFhUFJ6cDA0CjU3RUlKLy83U0E4T3NMUWhjRXhZ
        b0ZOM1haRXBIVm4rNzFEbDNMKzg5ZmMKLS0tIEppRnphc0o4TzN4cG95S0xUckZ5
        RWVTdTVhenQ3WDAxaC9DT1Z3VjlQa0kKxEW1MGB2PBzx/4gSA/DjrEq46pcE1aPW
        Fo3gkyRXL3ApIuJLr+f5PhsT9rgI4v0JcKEiZdVXxDGH0og8dDmnug==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-16T15:11:49Z"
  mac: ENC[AES256_GCM,data:XYSY1hBjoziU3HP7Y40MtJTXfdEsl+kDwWgk6IJaLxw4AEaqz8gpqZdqDAUgANkLrC9Cq4z/R+YePQqurK6s3gleyxbk7DG4LnX6IuswJJHurQZpfrK4M5E4pXUY5pkj2i6pVWDPxA1C77bt9fxWpgA6raSYG9WLo1QcHTjEIVE=,iv:feocoTvqZ3uen6UM1TwPX2zfizRkV9EBomwO51SuClA=,tag:NRBYotuO95wGItzDGeqXRg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
