apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:As1qghobI1WgzJ5FpSdPgoFoTVJUEZKPVuA413sxK+ULg0SEDv+ipmojznmuMnu926qlUtMgVEz3+DL5yfZTdZqb5FfP6qpk05w=,iv:LHJ7FCgkIjHVNbg/x+nzX9oR1oJhrx01JHIShCo/q3w=,tag:P2nQ5yD+lI43139t/5IwPA==,type:str]
sops:
  age:
    - recipient: age1d8dtvf39qwejljcn0jj7f29xtlnuav9sagfwy76g2asc0d4zjpqsu0s3pd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsY0txNThSZk0wSm1OOVNz
        NG9uVEl1dTRkU3kwUXEzV3N3M3hWcU9JU3o0CnhteVZEZXRxR1czenYrUTBXN01x
        ekoyUVVoZFdReXY4RExuelhaSzZhOGsKLS0tIDBBcitRVm0yaGx3eHczWjA5djFj
        SWxmMEUrV0FpV3lxa0NsMlE1RjgzYm8KGIJPHNHAR4Sj8S39QfGFQrU9FrapohU4
        DXRsvtGHfyarC7PYlJONxfe0LmJsMgQELKj7cIi6XWVl9uLM0Mc8Qw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-01T03:32:16Z"
  mac: ENC[AES256_GCM,data:YAERW/WhhY1l9BNatSoU7mBUVlqN+iNFcYjTyhM9mBjAxXf3FLaOkshnAUyxuNqFYlcODSXHJvqiUBavVkBI86fur8tD3cgoG0IpGUIoG7lIFkvahXGJiNLFzAKlbOjVW2GVxF7JjHxSjb3lgvpBiS2HrHnOei7dCZukpLl5PNQ=,iv:sowi7qBuh11Z8R25+kNhODTxnq4Bq4GWVq2ixOQYh68=,tag:yxeDIPi7dRHkWeYaCN+uXw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
