---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: snapshot-6h
  namespace: longhorn-system
spec:
  concurrency: 1
  cron: "0 */6 * * *"
  groups:
    - default
  retain: 4
  task: snapshot
