---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linkwarden
spec:
  refreshPolicy: Periodic
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: linkwarden-secret
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        DATABASE_URL: "postgresql://linkwarden:{{ .postgres_password | urlquery }}@${PG_HOST:=postgres-cluster-rw.database.svc.cluster.local}:5432/${PG_DATABASE:=${APP}}"
        NEXTAUTH_SECRET: "{{ .linkwarden_NEXTAUTH_SECRET }}"
        MEILI_MASTER_KEY: "{{ .linkwarden_MEILI_MASTER_KEY }}"
        AUTHENTIK_CLIENT_ID: "{{ .authentik_linkwarden_client_id }}"
        AUTHENTIK_CLIENT_SECRET: "{{ .authentik_linkwarden_client_secret }}"
  dataFrom:
    - extract:
        key: linkwarden
      rewrite:
        - regexp:
            source: "(.*)"
            target: "linkwarden_$1"
    - extract:
        key: linkwarden-postgres
      rewrite:
        - regexp:
            source: "(.*)"
            target: "postgres_$1"
    - extract:
        key: authentik-oidc
      rewrite:
        - regexp:
            source: "(.*)"
            target: "authentik_$1"
