---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./configmap.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  - ./externalsecret.yaml
patches:
  - patch: |-
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: ${APP}
        annotations:
          kustomize.toolkit.fluxcd.io/prune: disabled
    target:
      kind: PersistentVolumeClaim
      name: '\$\{APP\}'
