---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: gitlab
spec:
  name: gitlab
  owner: gitlab
  cluster:
    name: postgres-cluster
  schemas:
    - name: public
      owner: gitlab
  extensions:
    - name: pg_trgm
      ensure: present
    - name: btree_gist
      ensure: present
