---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: harbor
spec:
  name: harbor
  owner: harbor
  cluster:
    name: postgres-cluster
  schemas:
    - name: public
      owner: harbor
