---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: immich
spec:
  name: immich
  owner: immich
  ensure: present
  cluster:
    name: postgres-cluster
  extensions:
    - name: vector
      ensure: present
    - name: vchord
      ensure: present
    - name: cube
      ensure: present
    - name: earthdistance
      ensure: present
