---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/postgresql.cnpg.io/database_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: seerr
spec:
  name: seerr
  owner: seerr
  cluster:
    name: postgres-cluster
  schemas:
    - name: public
      owner: seerr
