---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "mise"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * 0" # once a week at midnight

jobs:
  mise:
    name: upgrade
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup mise
        uses: jdx/mise-action@v2
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Install dependencies
        run: mise upgrade --bump

      - name: Get diff of mise.toml
        run: |
          git diff > diff.patch

      - name: Generate Diff
        id: diff
        run: |
          cat diff.patch
          echo "diff<<EOF" >> $GITHUB_OUTPUT
          cat diff.patch >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          title: "chore(mise): upgrade dependencies"
          commit-message: "chore(mise): upgrade dependencies"
          body: |
            Upgraded dependencies found in `.mise.toml`:

            ```diff
            ${{ steps.diff.outputs.diff }}
            ```

            > [!TIP]
            > Merge this pull request and then run `mise upgrade --bump` on your workstation.
