---
name: "Publish devcontainer"

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: [".devcontainer/devcontainer.build.json"]
  pull_request:
    branches: ["main"]
    paths: [".devcontainer/devcontainer.build.json"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  publish-devcontainer:
    name: Publish devcontainer
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - if: ${{ github.event_name != 'pull_request' }}
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/${{ github.repository }}/devcontainer
          imageTag: base,latest
          configFile: .devcontainer/devcontainer.build.json
          push: ${{ github.event_name == 'pull_request' && 'never' || 'always' }}
