---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nas-backup
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: nas-backup-secret
    template:
      data:
        RCLONE_CONFIG: |
          [azure]
          type = azureblob
          account = {{ .AZURE_ACCOUNT_NAME }}
          sas_url = https://{{ .AZURE_ACCOUNT_NAME }}.blob.core.windows.net/?{{ .AZURE_SAS_TOKEN }}
  dataFrom:
    - extract:
        key: nas-backup-azure
