---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/upgrade.cattle.io/plan_v1.json
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: talos
spec:
  concurrency: 1
  exclusive: true
  nodeSelector:
    matchExpressions:
      - key: kubernetes.io/hostname
        operator: Exists
  postCompleteDelay: 2m
  secrets:
    - name: system-upgrade-controller
      path: /var/run/secrets/talos.dev
      ignoreUpdates: true
  serviceAccountName: system-upgrade-controller
  upgrade:
    image: ghcr.io/jfroy/tnu:0.4.3@sha256:fae8f88015eb231f5131e6c8f16e5f3b55d3c953697b8d4da264de4788661b6a
    args:
      - --node=$(SYSTEM_UPGRADE_NODE_NAME)
      - --tag=$(SYSTEM_UPGRADE_PLAN_LATEST_VERSION)
      - --powercycle
  version: ${TALOS_VERSION}