---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${SECRET_DOMAIN//./-}
spec:
  commonName: ${SECRET_DOMAIN}
  dnsNames: ["${SECRET_DOMAIN}", "*.${SECRET_DOMAIN}"]
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: ${SECRET_DOMAIN//./-}-tls
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: coder-${SECRET_DOMAIN//./-}
spec:
  commonName: coder.${SECRET_DOMAIN}
  dnsNames: ["coder.${SECRET_DOMAIN}", "*.coder.${SECRET_DOMAIN}"]
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: coder-${SECRET_DOMAIN//./-}-tls