---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/gateway_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: external
  annotations:
    external-dns.alpha.kubernetes.io/target: &hostname external.${SECRET_DOMAIN}
spec:
  gatewayClassName: cilium
  addresses:
    - type: IPAddress
      value: 10.60.82.10
    - type: IPAddress
      value: ::ffff:10.60.82.10
  infrastructure:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: *hostname
    labels:
      pool: ingress
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: "*.${SECRET_DOMAIN}"
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.${SECRET_DOMAIN}"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: ${SECRET_DOMAIN//./-}-tls
          - kind: Secret
            name: coder-${SECRET_DOMAIN//./-}-tls
    - name: https-coder
      protocol: HTTPS
      port: 443
      hostname: "*.coder.${SECRET_DOMAIN}"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: coder-${SECRET_DOMAIN//./-}-tls